label.patch, pipeline-ff.patch, run.sh
Changes required compared to a regular installation:
* Tekton taskruns controller needs to add the correct annotation for the pod to be scheduled. This should be done by an external component like the deployment splitter.
* Sidecar checking code is broken: taskruns controller creates the pod, then after a while, add a custom annotation READY. This annotation is not synced with the physical cluster. If the feature is not turned off, pods hang forever.
* All Tekton CRDs need to be create on.
=> run Tekton controller

ckcp/docker/ckcp/entry.sh, ckcp/run.sh, local/run.sh, oci-bundle.patch, pvc.patch
1. Checkout this PR and deploy KCP+Pipelines in Kubernetes with `./run.sh pipelines`
2. Checkout infra-deployments
3. Edit `hack/build/build.sh` to use `BUNDLE=quay.io/mkovarik/build-templates-bundle:noop-utils`
4. Run `./hack/build/quick-noop-build.sh` with kubeconfig pointing to KCP.
Output:
```
$ k get prs,trs,pods
NAME                                            SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
pipelinerun.tekton.dev/noop-2022-02-17-094347   True        Succeeded   2m24s       82s
NAME                                              SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
taskrun.tekton.dev/noop-2022-02-17-094347-merge   True        Succeeded   88s         82s
taskrun.tekton.dev/noop-2022-02-17-094347-start   True        Succeeded   2m14s       105s …
```
=> Working branch for running noop pipeline of build-definitions

ckcp/README.MD, ckcp/gitops.sh
Use the same keywords (pipelines, triggers) for gitops.sh and test.sh.
=> Clean-up gitops.sh

.gitignore, gitops/pipelines-controller.yaml, gitops/pipelines-crds.yaml, gitops/pipelines/pipelines-crds/overlays/patched/kustomization.yaml, gitops/triggers-controller.yaml, gitops/triggers-crds.yaml, gitops/triggers-interceptors.yaml, gitops/triggers/triggers-crds/interceptors/deployments.apps.yaml, gitops/triggers/triggers-crds/interceptors/kustomization.yaml, gitops/triggers/triggers-crds/interceptors/pods.yaml, gitops/triggers/triggers-crds/interceptors/services.yaml, kcp/README.MD, kcp/common.sh, kcp/deploy.sh, kcp/manifests/kcp/argocd-manager.yaml, kcp/manifests/kcp/plnsvc-manager.yaml, kcp/manifests/plnsvc/argocd-manager.yaml, kcp/manifests/plnsvc/kcp-manager.yaml, kcp/manifests/plnsvc/namespace.yaml, kcp/reset.sh, kcp/test.sh, sink.patch
Change summary:
- Modify gitops manifests to always use cluster names. This helps handling the deployment differences between local dev and staging.
- Add `kcp/login.sh` to automate the action of logging in the staging environment.
- Add `kcp/deploy.sh` to automate the deployment to the staging environment
The required resources are now deployed by ArgoCD, except for `triggers-interceptors`. We believe the issue is linked to https://github.com/kcp-dev/kcp/issues/730.
=> Deploy CRDs on KCP staging instances through ArgoCD

DEVELOPMENT.md, ckcp/README.MD, ckcp/build.sh, ckcp/docker/ckcp/Dockerfile, local/.utils, local/kind/setup.sh
- Use ALLOW_ROOTLESS environment variable to enable rootless podman.
- Update detect_container_engine to run rootless podman if desired.
- Use detect_container_engine function in building ckcp image.
- Use docker.io image references in ckcp Dockerfile.
Signed-off-by: Adam Kaplan <adam.kaplan@redhat.com>
=> development: Use Rootless Podman

local/kcp/start.sh
With the 0.4 release, removed the flags that are no more in use.
=> Upgraded kcp to release-0.4 for the local dev env

ckcp/README.MD, ckcp/gitops.sh, ckcp/run.sh, local/.utils, local/argocd/setup.sh, local/kcp/start.sh, local/kind/setup.sh
https://issues.redhat.com/browse/PLNSRVCE-236
This PR fixes incompatibility issues with "local" & ckcp scripts when running on Mac OS and a case when ArgoCD is being installed on existing kind cluster (created from previous script run).
Also contains some fixes recommended by shellcheck.
1. For verification of local scripts:
```bash
NO_ARGOCD=true ./local/kind/setup.sh
NO_ARGOCD=false ./local/kind/setup.sh
```
2. For verification of ckcp scripts:
```bash
cd ckcp
./gitops.sh -h
./gitops.sh -a pipelines
./gitops.sh --debug
./gitops.sh --all
```
=> fix: update local & ckcp scripts, fix MacOS compat.

.gitleaks.toml, gitops/pac/README.md, gitops/pac/manifests/ci-runner-ns.yaml, gitops/pac/manifests/ingress.yaml, gitops/pac/manifests/kustomization.yaml, gitops/pac/manifests/repository.yaml, gitops/pac/manifests/webhook-cfg-secret.yaml, gitops/pac/setup.sh
Add manifests, a script and instructions for the installation of Pipelines as Code and the registration of repositories.
Goal:
Pipelines as Code can be leveraged for automating the registration of clusters to Argo CD and kcp when their kubeconfig file gets added to a git repository, following a GitOps approach.
=> Pipelines as Code: installation and repository registration

DEVELOPMENT.md, local/kind/setup.sh
Ingress deployments on the local kind clusters can fail due to the
kernel limiting the number of file watch instances. This can be fixed by increasing
the number of file watches and instances for the machine.
Signed-off-by: Adam Kaplan <adam.kaplan@redhat.com>
=> Document inotify issue deploying ingress

DEVELOPMENT.md, docs/argocd.md, gitops/credentials/kubeconfig/.gitignore, gitops/credentials/kubeconfig/README.md, gitops/credentials/kubeconfig/compute/.gitignore, gitops/environment/compute/base/argocd-rbac/argo-syncer-role.yaml, gitops/environment/compute/base/argocd-rbac/argo-syncer-rolebinding.yaml, gitops/environment/compute/base/argocd-rbac/argo-tekton-role.yaml, gitops/environment/compute/base/argocd-rbac/argo-tekton-rolebinding.yaml, gitops/environment/compute/base/argocd-rbac/kustomization.yaml, gitops/environment/compute/base/namespaces/kcp-syncer-ns.yaml, gitops/environment/compute/base/namespaces/kustomization.yaml, gitops/environment/compute/base/namespaces/management-ns.yaml, gitops/environment/compute/base/namespaces/tekton-ns.yaml, gitops/pac/.tekton/argo-registration.yaml, gitops/pac/README.md, gitops/pac/setup.sh, images/argocd/Dockerfile, images/argocd/register.sh
Goal: Providing a GitOps approach to automate the registration of clusters into Argo CD.
Content: 
- a PipelineRun integrated into Pipelines as Code, which automate the registration from a repo push or PR
- a container image for supporting the Task
- a script with the necessary logic
- manifests for namespaces and rbac
- documentation
=> Automation of the registration of clusters into Argo CD  following a GitOps approach

local/kind/setup.sh
For local development
- Added logic to have a kubeconfig file, which points to an IP, which is accessible from the KinD network instead of localhost.
This is useful when the cluster for instance needs to be registered to an Argo CD server running on a KinD cluster.
- Removed the generation of manifests for workloadclusters as in pull mode they are now generated by the syncer command.
=> local dev: kubeconfig with IP instead of localhost

gitops/pac/.tekton/argo-registration.yaml, images/argocd/Dockerfile
- Similar to the registration to kcp "push" is the right event and not "pull request". The workflow only need to get triggered when the change has been merged.
- Align the permissions on binaries with what is done for the kcp image
=> Change event triggering Argo CD registration from pull request to push

DEVELOPMENT.md, docs/kcp-registration.md, gitops/pac/.tekton/kcp-registration.yaml, gitops/pac/README.md, images/kcp-registrar/Dockerfile, images/kcp-registrar/register.sh, local/kcp/pipelines-service-org.yaml, local/kcp/start.sh
Goal: Providing a GitOps approach to automate the registration of clusters into kcp.
Content:
- a PipelineRun integrated into Pipelines as Code, which automate the registration from a repo push or PR
- a container image for supporting the Task
- a script with the necessary logic
- documentation
=> Automation of the registration of clusters into kcp following a GitOps approach

exploration/argocd-external/images/argocd-registrar/Dockerfile, images/kcp-registrar/Dockerfile, images/kcp-registrar/register.sh
Add $HOME environment variable to container images as it is used:
- for docker credentials
- for storing kubectl cache
=> Add $HOME environment variable to container images

exploration/argocd-external/gitops/pac/.tekton/argo-registration.yaml, gitops/pac/.tekton/kcp-registration.yaml
Use the ghcr repository for the pipelines-service.
Instruct PaC to fetch remote Tasks if necessary.
=> Use ghcr repository and instruct PaC to fetch remote Tasks if necessary

.github/workflows/kcp-registrar-image.yaml, README.md, ckcp/openshift/overlays/dev/kustomization.yaml, ckcp/openshift_dev_setup.sh, ckcp/test.sh, docs/phase1_limitations.md, images/kcp-registrar/Dockerfile, images/kcp-registrar/register.sh, local/kcp/start.sh
**Changes**
1. Modified KCP image to [release-0.5](https://github.com/kcp-dev/kcp/pkgs/container/kcp/24100239?tag=release-0.5)
2. Modified  KCP Syncer image to [release-0.5](https://github.com/kcp-dev/kcp/pkgs/container/kcp%2Fsyncer/24099863?tag=release-0.5 )
3. Modified ./ckcp/test.sh to look for namespace with proper label
4. Modified ./ckcp/test.sh for PipelineRun case by removing serviceAccountName property
**Known Issue**
1. When executing `./ckcp/test.sh pipelines`, the PipelineRun, such like `test-pipelinerun-xxxx` will fail due to the SA token secret being renamed from `default-token-xxxx` in icp to  `kcp-default-token-xxx` on the workload cluster.  It couldn't find the secret.
2. `./ckcp/test.sh` couldn't run the trigger cases, It needs to expose the event listeners through a …
=> Modified kcp version to release-0.5

ckcp/openshift_dev_setup.sh
**Changes:**
It fixed minor issues
- Fixed the if condition, now it could work in both Mac and Linux
- It could correctly handle the output message for command `kubectl cert-manager check api`, we hope it doesn't print out the message
=> fixed minor issues about cert-manager

DEVELOPMENT.md, local/kind/setup.sh
For using kind with podman KIND_EXPERIMENTAL_PROVIDER needs to be set. It was not consistently done in the script and relying on the environment variable being preset.
Besides that PODMAN_CMD was redundant as CONTAINER_ENGINE is already set by the .utils script
=> Fix issue with KIND_EXPERIMENTAL_PROVIDER not being properly set

images/kcp-registrar/Dockerfile, images/kcp-registrar/register.sh
The logic is mostly unchanged, except:
1. `register.sh` is copied last to speed up image creation time on the
local dev env;
2. the kubeconfig are copied to a tmp folder to workaround ro permissions
in the container;
3. all clusters are always processed.
Item #3 is possible because the cluster registration is idempotent as
of kcp release-0.5.
Item #3 is desirable because if anything bad happens while setting up
the cluster, the recovery would require a manual action to delete the
syncer on KCP.
=> Clean up kcp_registrar

docs/kcp-registration.md, gitops/sre/.tekton/kcp-registration.yaml, images/kcp-registrar/Dockerfile, images/kcp-registrar/register.sh
- KCP_TAG variable has been added to the script but not explicitely declared. It is useful when running the script locally and for documentation purpose
- KCP_WORKSPACE was missing in the PipelineRun
=> Fix a couple of issues with the registration

images/kcp-registrar/register.sh
The ServiceAccount used may not have access to the root workspace. Switching
workspaces is unnecessary if we're already in the target workspace.
=> fix: KCP registration process may fail when switching workspace

gitops/argocd/tektoncd/kustomization.yaml
It seems TektonConfig is not being applied peoperly due to a permission issue. This PR reverts TektonConfig until the issue is resolved.
Signed-off-by: Avinal Kumar <avinkuma@redhat.com>
=> Revert TektonConfig until issue is resolved

gitops/pac/README.md, gitops/pac/setup.sh
This PR contains:
- Set the version of PaC installation from latest release.yaml to version 0.10.0 in pac/setup.sh
- Updated Readme to reflect that users need to set CONTROLLER_INSTALL to true so that version 0.10.0 of PaC is installed through the script.
=> PaC setup script and readme changes

ckcp/openshift_dev_setup.sh, workspace.yaml
Since the directory is automatically removed when the script is
executed, use a tmpdir by default and give the option to the user to
specify an alternate directory.
Removed unused workspace.yaml
Format script (remove double spaces, improve indentation).
=> fix: Add work-dir option to ckcp deployment script

ckcp/openshift_dev_setup.sh, images/kcp-registrar/register.sh
This is to be able to sync *networkpolicies* between kcp-workspaces and the computes.
=> Added NetworkPolicy resource to the kcp-syncer

gitops/pac/setup.sh
Issue:
Because the generated path of temp dir is different in the both Mac and Linux, the resource path of `gitops/pac/manifests`  is not correct in kustomization.yaml.
**Changes:**
Generate a relative path of `gitops/pac/manifests` and then refer to the relative path in kustomization.yaml.
=> fix a minor issue for pac setup

gitops/argocd/tektoncd/tekton-config.yaml
- This PR is about the migration of [this](https://github.com/redhat-appstudio/infra-deployments/blob/main/components/build/openshift-pipelines/) as part of kcp transition Epic.
- We are installing and managing OpenShift Pipelines via the operator using GitOps (ArgoCD). Hence, no changes with the installation itself.
- Regarding the config, all the other parameters are either not necessary or available by default. Have added support for oci-bundles in this PR.
- Pipelines-as-Code will be taken up in a separate story/PR.
=> PLNSRVCE-478 : Migration: openshift-pipelines

ckcp/openshift_dev_setup.sh
with k8s 1.24, --dry-run must be used with a value or either client or server. It throws this error otherwise:
```
[bnr@bnr pipelines-service]$ kubectl create -f /home/bnr/workspace/pipelines-service/ckcp/openshift/base/certs.yaml --dry-run
error: --dry-run flag without a value was specified. A value must be set: "none", "server", or "client".
```
=> Fixed issue with --dry-run option

DEVELOPMENT.md, ckcp/openshift_dev_setup.sh, docs/kcp-registration.md, docs/sre/examples/providers/environment/kcp/kustomization.yaml, docs/sre/examples/single_cluster/environment/kcp/kustomization.yaml, gitops/README.md, gitops/kcp/registration/clusterrole.yaml, gitops/kcp/registration/clusterrolebinding.yaml, gitops/kcp/registration/kustomization.yaml, gitops/sre/.tekton/kcp-registration.yaml, gitops/sre/environment/kcp/kustomization.yaml, images/kcp-registrar/register.sh
The process to bind to an APIExport now requires the right RBAC to be
granted to the user(s).
=> Configure SyncTarget workspace and update APIBinding documentation

docs/kcp-registration.md, images/kcp-registrar/register.sh
**Changes:**
To avoid the error that Syncer namespace is greater than 63, changed the behavior of producing Syncer namespace. 
- use cluster name if <= 43 chars
- use hash otherwise
=> fixed the behavior of producing syncer namespace

docs/gateway.md
Amend gateway documentation to refer to kcp GLBC (instead of the PoC implementation)
=> Amend gateway documentation

DEVELOPMENT.md
Document the solution for when the deployment of kind with ArgoCD fails
because the default podman settings for pids does not allow the processes
to spawn.
=> Add troubleshooting section about podman pids_limit

images/kcp-registrar/Dockerfile
This [commit](https://github.com/openshift-pipelines/pipelines-service/commit/25695419e862bd0068c47f41c446130b83cc2474#diff-010d75c07c9fda576ad68d1bf93347cf3ded384b058db9926fcd2e52ceafb308R161) added its use in the script
=> Add the find utility to the image used for kcp registration 

DEVELOPMENT.md, local/kcp/start.sh
- remove flag `--discovery-poll-interval`, which is not available anymore in the latest 0.6 release
- do not start ingress components that are not compatible anymore (to be replaced by glbc when ready)
=> update script for starting kcp locally

.github/workflows/access-setup-image.yaml, .github/workflows/argocd-registrar-image.yaml, .github/workflows/cluster-setup-image.yaml, .github/workflows/gateway-deployment-image.yaml, .github/workflows/shellcheck-image.yaml, .tekton/shellcheck-yaml-lint-pipeline.yaml, DEVELOPMENT.md, exploration/argocd-external/gitops/pac/.tekton/argo-registration.yaml, gitops/sre/.tekton/cluster-setup.yaml, gitops/sre/.tekton/gateway-deployment.yaml, gitops/sre/.tekton/kcp-registration.yaml, images/access-setup/README.md
- Created a new organization in quay.io called redhat-pipeline-service
- Created repositories in quay.io in order to upload respective images
- Created a robot account in order to grant access to GitHub actions to upload images to quay.io
- Updated references from ghcr.io to quay.io throughout the repo - both in GitHub actions and PipelineRuns where it was being used
- Added access-setup workflow.
- Tested it on my repo to verify its working fine (similar steps were followed on my quay account and github repo)
=> PLNSRVCE-530: Make changes in the repo to move images from ghcr.io to quay.io

gitops/sre/environment/kcp/kustomization.yaml
Fixed referenced github url in `./gitops/sre/environment/kcp/kustomization.yaml` to point to `openshift-pipelines/pipelines-service`
=> Fix referenced github url 

DEVELOPMENT.md, local/kcp/start.sh, local/kind/setup.sh, local/utils.sh
- Add kubectl and jq in prechecks
- Add information about exit status: normal exit(including ctrl-C) vs failure
- Fix wait_command: now program exits if command is not ready and
timeout expires
- Fix kubectl-kcp plugin path
=> Fix minor issues in local install scripts

ckcp/openshift_dev_setup.sh
Removed precheck for kubectl cert-manager plugin because the script doesn't rely on  kubectl cert-manager plugin
=> removed precheck for kubectl cert-manager plugin

local/kcp/pipelines-service-org.yaml, local/kcp/start.sh
Switch to the imperative creation of organization workspace to get the new RBAC (clusterrole and clusterrolebinding in root workspace) automatically set up.
=> local dev: Switch to the imperative creation of organization workspace

gitops/README.md
2 links are broken in the README of the gitops repository.
=> Fix broken doc links

gitops/argocd/tektoncd/allow-argocd-to-manage.yaml, gitops/argocd/tektoncd/kustomization.yaml, gitops/argocd/tektoncd/tekton-config.yaml
- Only prune taskruns
- Added ClusterRole and ClusterRoleBinding for granting permission to
argocd serviceaccount to be able to patch TektonConfig
- Added sync wave to the TektonConfig patch for precaution, ensures
that TektonConfig CRD is available before patching
- Fixes PLNSRVCE-355
```sh
k auth can-i --list   --as=system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller | grep tektonconfigs
tektonconfigs.operator.tekton.dev                                    []                                          []               [get watch list patch]
``` 
```yaml
apiVersion: v1
items:
- apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
annotations:
argocd.argoproj.io/sync-wave: "1"
kubectl.kubernetes.io/last-applied-configuration: | …
```
=> Fix taskrun pruning in workload cluster

ckcp/openshift/base/deployment.yaml
kcp-in-container (ckcp) currently has CPU and memory requests that make
it difficult to schedule on a standard IPI cluster. In testing, the
following behavior was observed:
- Initial memory usage hits 177Mi, is never lower.
- kcp memory increases to ~500Mi once syncer is deployed.
- CPU usage rarely exceeds 0.1 CPU per minute. 100m CPU request is
typical for a system workload.
Partially addresses #118
=> ckcp: Optimize resource requests and limits

.github/workflows/local-dev-ci.yaml
**Changes:**
Upgraded kcp to  release-0.7 in ckcp CI, the changes include:
1. kcp:  release-0.7 
2. kubectl: 1.24.3
3. go:  v1.18
=> upgrade kcp to release-0.7 in CI of local dev environment

images/access-setup/content/bin/common.sh
**Issue:**
shellcheck reported the following issue:
```
In ./images/access-setup/content/bin/common.sh line 41:
for i in {1..5}
^-^ SC2034: i appears unused. Verify use (or export if used externally).
```
**Solution:**
use the name `_` as variable , I found the solution from this [link](https://github.com/koalaman/shellcheck/issues/1134)
=> fixed shellcheck issue SC2034 

images/access-setup/content/bin/setup_kcp.sh, images/gateway-deployment/install.sh, images/kcp-registrar/register.sh
This is for supporting the creation of compute workspaces under root (default is organization under root).
=> Explicitly set the type by workspace creation

ckcp/test.sh
A change in kcp broke the function retrieving the namespace
on the compute cluster. This change fixes the issue and
adds a test to ensure that the scripts fails nicely if the
issue was to happen again.
=> bugfix: ckcp/test.sh

images/access-setup/Dockerfile, images/cluster-setup/Dockerfile, images/kcp-registrar/Dockerfile, test/images/shellcheck/Dockerfile
**Changes:**
Fixed Dockerfile issues that hadolint reported.
When this PR is merged, the CI [PR](https://github.com/openshift/release/pull/31602) can be merged and enable hadolint CI.
**Verify:**
Execute the following command to verify it
```
$ docker run -it --rm --mount type=bind,source="<path of pipelines-service >",target=/workspace ghcr.io/hadolint/hadolint:latest-debian find /workspace -name Dockerfile -exec hadolint -c test/config/hadolint.yaml {} +
```
=> fix issues that hadolint reported

ckcp/openshift_dev_setup.sh
Make sure to check for binaries used by the script, beforehand, if it's not present fail as early as possible. For example in our case we didn't know `yq` is supposed to be part of the container image:
e.g. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31857/rehearse-31857-pull-ci-redhat-appstudio-managed-gitops-main-managed-gitops-e2e-tests-on-kcp/1565006131774885888#1:build-log.txt%3A37
=> Check for local binaries

ckcp/openshift_dev_setup.sh, images/cluster-setup/Dockerfile, images/cluster-setup/bin/install.sh, images/cluster-setup/bin/utils.sh
**Purpose**
When you first install cert-manager, it will take a few seconds before the cert-manager API is usable. This change is to improve ckcp deployment to avoid the issue that the cert-manager API is usable while deploying ckcp.
**Changes**
1. Added a retry loop to ensure ckcp resources are deployed to OCP successfully
2. Minor changes to print out error messages when it fails
3. Update `check_cert_manager` function to reuse `check_deployments` function for validating cert manger deployment
=> Improve ckcp deployment to avoid cert-manger error

gitops/argocd/tektoncd/kustomization.yaml, gitops/argocd/tektoncd/tekton-config.yaml
This PR will allow the Argo CD to skip the verification of `tektonconfig` resource which is not available on the server before Openshift-Pipelines operator is deployed, else it would always end in error - `the server could not find the requested resource`.
Jira - [629](https://issues.redhat.com/projects/PLNSRVCE/issues/PLNSRVCE-629?filter=allopenissues)
=> fix tektonconfig sync

local/kcp/start.sh
PARAMS was not tokenized properly when passed through an environment variable.
=> Fix handling of PARAMS in local/kcp/start.sh

local/kcp/start.sh
* Allow KCP_DIR to be a relative path
* Checkout and build kcp if KCP_DIR is specified but empty
Example of a command solved by this PR: `rm -rf ./work; KCP_DIR=./work/kcp ./start.sh`
=> Improve UX of local/kcp/start.sh

ckcp/test.sh
**Changes**
Fixed issue by specifying a WORK_DIR as parameter. so it could find the correct kcp and compute's kubeconfig files. For now it only support testing pipelines.
After you execute the `ckcp/openshift_dev_setup.sh` command, you could use `ckcp/test.sh` to verify if pipeline-service works. The command example as below
```
WORK_DIR=./ckcp/workdir CASES=pipelines ./ckcp/test.sh
```
=> fixed issue of testing pipelinerun

images/access-setup/content/bin/setup_compute.sh
Similar to this [PR](https://github.com/openshift-pipelines/pipeline-service/pull/162), it will fix - yq can't access root file system when installed via snap for `setup_compute.sh`
=> fix issue with yq in setup_compute script

images/kcp-registrar/Dockerfile
Includes some cosmetic changes:
- Double quoting strings
- Use the same options for curl
- Creation of KCP_VERSION_SHORT var instead of inline processing
=> Fix missing yq dependency in kcp-registrar Dockerfile

ckcp/openshift_dev_setup.sh, images/access-setup/content/bin/common.sh, images/access-setup/content/bin/setup_compute.sh, images/access-setup/content/bin/setup_kcp.sh, images/cluster-setup/bin/install.sh, images/cluster-setup/bin/utils.sh, images/kcp-registrar/register.sh
Improving ckcp output readability from:
```
➜ /repos/plnsvc/pipelines-service % git:(main) ./ckcp/openshift_dev_setup.sh
Working directory: /tmp/tmp.xAXTA5oppU
[openshift-gitops]
- OpenShift-GitOps: OK
- Argo CD dashboard: ..........................................OK
- Argo CD URL: https://openshift-gitops-server-openshift-gitops.apps.ci-ln-6114gpt-76ef8.origin-ci-int-aws.dev.rhcloud.com
- Argo CD Login: OK
- Register host cluster to ArgoCD as 'plnsvc':
INFO[0000] ServiceAccount "argocd-manager" created in namespace "kube-system"
INFO[0000] ClusterRole "argocd-manager-role" created
INFO[0001] ClusterRoleBinding "argocd-manager-role-binding" created
OK
[cert-manager]
- OpenShift-Cert-Manager:
- cert-manager: ....Exists, Ready
- cert-manager-cainjector: Exists, Ready
- cert-manager-webhook: …
```
=> Improve readability of ckcp script output via a better indentation

ckcp/openshift_dev_setup.sh, config/config.yaml, images/kcp-registrar/register.sh
Custom resources to sync with kcp can now be provided as a parameter for register.sh script.
Also CR_TO_SYNC was renamed to CRS_TO_SYNC since we are dealing with multiple CRs
=> Provide CRs to sync as parameter in register script

ckcp/openshift_dev_setup.sh
A common feedback received on our script is that kcp kubeconfig is not easily visible for users' to get access to. Printing it at the end of the script.
=> Print kubeconfig of kcp and cluster at the end of ckcp script

.github/workflows/kcp-upgrade.yaml, images/kcp-upgrade/upgrade.sh
Modify upgrade_kcp workflows
- to not fail the workflows when the kcp version is already the
latest one instead gracefully exit the workflow by skippng the
next step.
=> Modify upgrade_kcp workflows

.github/workflows/build-push-images.yaml, images/quay-upload/image-upload.sh, images/update-pipeline-service/Dockerfile, images/update-pipeline-service/bin/gitlab_open_mr.sh, images/update-pipeline-service/bin/update.sh, test/images/quay-upload/Dockerfile, test/images/quay-upload/image-upload.sh
Context:
Gitlab CI uses cluster-setup and kcp-registrar images with 'latest' tag at the moment. We want to provide the latest commit SHA as the tags instead of latest. I am working on automating this process where we always fetch the last commit ID and provide that as the tag in Gitlab. Once this is merged, it will trigger a CI to update our staging cluster with the latest code.
Problem:
Now, the Github action build-push-images.yaml is based on path filtering. It would only build and create new images only when there are changes to that image content. Otherwise, it will just have a older commit tag as the latest. So there is a possibility of non-existent image tag which Gitlab will try to fetch and fail. 
Solution:
This PR that **does not** build a new image if there are no changes but …
=> PLNSRVCE-671 : Automate the process to upgrade pipeline-service on staging cluster

.github/workflows/kcp-upgrade.yaml, images/kcp-upgrade/upgrade.sh
The previous workflow would always be successful because it could not discriminate between the script failing and no update being required.
Changes have been implemented to have the workflow fail in case the script fails, and be successul if there's no update required.
=> Fix kcp-upgrade workflow

test/images/quay-upload/image-upload.sh
The below Github action is failing. This PR fixes the issue.
https://github.com/openshift-pipelines/pipeline-service/actions/runs/3216908688/jobs/5259289529#step:8:11
=> Fixes failing github action step push to quay.io due to variable name mismatch

images/update-pipeline-service/bin/gitlab_open_mr.sh, images/update-pipeline-service/bin/update.sh
Currently, Gitlab auto pr creation is failing due to incorrect job name given in the script that fetches the current commit ID. This fix fixes the name which fixes the issue with empty MR being opened.
=> Fix gitlab pipeline - Modify the name of the job used in Gitlab ci to fetch the current commit

exploration/argocd-external/images/argocd-registrar/Dockerfile, images/access-setup/Dockerfile, images/cluster-setup/Dockerfile, images/gateway-deployment/Dockerfile, images/kcp-registrar/Dockerfile, images/update-pipeline-service/Dockerfile, test/images/devenv/Dockerfile, test/images/quay-upload/Dockerfile, test/images/shellcheck/Dockerfile, test/images/vulnerability-scan/Dockerfile
Using the SHA will enable us to trigger the rebuild of images when new images are made available, especially in the case when the new image solves a vulnerability issue.
=> Update Dockerfiles to use SHA instead of tags

.github/workflows/build-push-images.yaml
Github action to push images into quay is failing because a the URL sent during an API call is incorrect
URL : https://quay.io/api/v1/repository/$image_path/tag/
Current value of image_path : quay.io/redhat-pipeline-service/access-setup
This PR will change that to : redhat-pipeline-service/access-setup
=> Updated the registry value used while sending a GET API request on quay-upload/image-upload.sh

test/images/devenv/Dockerfile
SHA tested with:
```
> skopeo inspect docker://quay.io/podman/stable:v4 | jq ".Digest" -r
sha256:e968245017a54e31fec7583c589f1d68e5a14723e76d29861a887865c09084a0
> podman pull quay.io/podman/stable@sha256:e968245017a54e31fec7583c589f1d68e5a14723e76d29861a887865c09084a0
Trying to pull quay.io/podman/stable@sha256:e968245017a54e31fec7583c589f1d68e5a14723e76d29861a887865c09084a0...
Getting image source signatures
Copying blob aaaf7db17b6d done  
Copying blob 72f8478ad099 done  
Copying blob 410ecb83fc0c done  
Copying blob be8c68cbb7d2 done  
Copying blob 62946078034b skipped: already exists  
Copying blob 81b10f9f3fc1 done  
Copying blob dc6f33153a37 done  
Copying blob f523c9884953 done  
Copying config 6a854277ec done  
Writing manifest to …
```
=> Upgrade SHA for devenv image

.github/workflows/individual-image-scanner-quay.yaml
Now, [IndividualImageScannerQuay](https://github.com/openshift-pipelines/pipeline-service/blob/main/.github/workflows/individual-image-scanner-quay.yaml) will run after [BuildPushImage](https://github.com/openshift-pipelines/pipeline-service/blob/main/.github/workflows/individual-image-scanner-quay.yaml) workflow and will be skipped if somehow BuildPushImage fails.
=> PLNSRVCE-646 : Sync workflows

.github/workflows/build-push-images.yaml
Wrong env variable is used for the password
=> Fix build-push-images.yaml

.github/workflows/individual-image-scanner-quay.yaml, ckcp/hack/util/reset_ckcp.sh
* Bug in invoking one of the steps in the `individual-image-scanner-quay.yaml`
* Conceal error when a resource is not found when running `reset_ckcp.sh` using `--ignore-not-found=true`
=> fix workflow and reset_ckcp.sh

test/images/devenv/Dockerfile
Podman seems to remove some images, breaking our CI. Since this image is not a production image, using the x.y.z tag is good enough.
=> Use full version tag for the podman image

ckcp/openshift_dev_setup.sh, gitops/README.md, gitops/sre/environment/kcp/workspace-controller/base/kustomization.yaml, gitops/sre/environment/kcp/workspace-controller/overlays/kustomization.yaml, images/kcp-registrar/bin/register.sh
This PR includes the following changes:
- Added a new kustomization folder for workspace-controller under gitops/sre/.../kcp
- Modified register.sh under kcp-registrar to install workspace controller
- Modified the order in which check_cr_sync is called because we need to verify all the resources are available before applying the controller manifests. As part of this change, moved the function from ckcp to register.sh script.
- Updated README under gitops
Local run output (trimmed):
```
Configuring KCP workspace
clusterrole.rbac.authorization.k8s.io/apibinding:kubernetes unchanged
clusterrolebinding.rbac.authorization.k8s.io/apibinding:kubernetes:all-users unchanged
- Sync CRDs to KCP: OK
Deploying Workspace Controller into the workspace
namespace/settings-pipeline-service-controller …
```
=> PLNSRVCE-777 : [M9]Deploy the workspace controller onto the staging cluster

shared/config/dependencies.yaml, test/images/devenv/Dockerfile, test/images/devenv/install.sh
Update dependencies to include and install grpc_cli
grpc_cli is used as part of the tests for tekton results to ensure results are stored correctly
=> Update dependencies to include grpc_cli

shared/config/dependencies.yaml, test/images/devenv/install.sh
The image was not build because of an issue when extracting tkn from the archive. Adding the '--no-same-owner' option solves the issue.
=> Fix devenv build

ckcp/hack/util/reset_ckcp.sh
The name of the kubeconfig is not static, so the script has been modified to look for any kubeconfig file
=> Fix reset_ckcp.sh when using a custom workspace

developer/ckcp/hack/util/reset_ckcp.sh, developer/ckcp/openshift_dev_setup.sh, operator/gitops/argocd/argo-apps/cert-manager-operator.yaml
After layout reorg in 7797894, the cert-manager-operator path has changed, this commit updates a reference to the path in argo-cd app and simplifies cert-manager deployment check.
=> Fix cert-manager path in argocd app

.github/workflows/argocd-registrar-image.yaml, .github/workflows/build-push-images.yaml, .github/workflows/individual-image-scanner-quay.yaml, .github/workflows/kcp-upgrade.yaml, .github/workflows/periodic-scanner-quay.yaml
We get the below warning in our Github actions at the moment. This PR fixes the issue.
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> PLNSRVCE-778 : Replacing set-output with GITHUB_OUTPUT as it is deprecated in Github actions

ci/images/quay-upload/image-upload.sh, developer/ckcp/README.md, developer/docs/DEVELOPMENT.md, developer/images/devenv/run.sh, developer/local/kind/setup.sh, operator/images/access-setup/content/bin/setup_compute.sh
Some developers do not use podman, or podman is causing trouble on their platform (e.g. macOs).
Scripts have been changed to use in order of preference:
- CONTAINER_ENGINE if set by the user
- podman
- docker
Linked to #276
=> Use CONTAINER_ENGINE instead of podman

developer/ckcp/README.md, developer/ckcp/config.yaml, developer/ckcp/openshift_dev_setup.sh, developer/local/kcp/start.sh, operator/images/access-setup/content/bin/setup_kcp.sh, operator/images/kcp-upgrade/upgrade.sh
The workspace in which the service is deployed can now be configured by changing the kcp.workspace value in config/config.yaml.
The structure of the config.yaml file has been modified to improve readability by grouping values together when possible.
=> Allow workspace to be configured when deploying ckcp

operator/images/update-pipeline-service/bin/gitlab.sh
Improper ordering of 2 function calls was triggering an 'unbound variable' error
=> fix update-pipeline-service

ci/images/vulnerability-scan/common/utils.sh, ci/images/vulnerability-scan/scan-image.sh, ci/images/vulnerability-scan/scan.sh
From the logs of a latest run. Instead of the value of res being 0 or 1, the script exits prematurely causing the value to be set to some string. This PR fixes this issue.
```
Run res= Check the full report here: https://quay.io/repository/redhat-pipeline-service/vulnerability-scan/manifest/sha256:92f5cf046[1](https://github.com/openshift-pipelines/pipeline-service/actions/runs/3389846804/jobs/5633369718#step:9:1)bdedb54e66bf2e6a489b16f67ef941aad27cf62f1f25976c29736f?tab=vulnerabilities 
/home/runner/work/_temp/00184d58-34aa-45fb-90ff-56d51ab33496.sh: line 1: Check: command not found
Error: Process completed with exit code [12](https://github.com/openshift-pipelines/pipeline-service/actions/runs/3389846804/jobs/5633369718#step:9:13)7.
```
=> Capture return status in the function call inline to fix the issue with vulnerability scanners

operator/gitops/argocd/tekton-results/configmap.yaml, operator/gitops/argocd/tekton-results/deployment.yaml
Create configmap on cluster and mount in the tekton-results api container. 
This will fix an issue where results is trying to load the config file and gives an error. 
It will also allow configuring tekton results by file in the future if needed.
=> Create configmap for configuring tekton-results

operator/docs/sre/examples/providers/credentials/secrets/aws-secret-manager.yaml, operator/docs/sre/examples/providers/credentials/secrets/bitwarden.yaml, operator/docs/sre/examples/single_cluster/credentials/manifests/compute/tekton-results/tekton-results-secret.yaml, operator/docs/sre/examples/single_cluster/credentials/secrets/bitwarden.yaml, operator/gitops/sre/credentials/secrets/README.md, operator/images/cluster-setup/bin/install.sh
- Fetch secrets from Bitwarden and replace those values in the corresponding files.
- Docs directory updated with relevant examples.
- SRE directory updated with README.
- Enable/disable tracing to hide secrets.
Local run output (truncated):
```
- Deploy compute:
[Bitwarden]:   
bitwarden.yaml file exists. Checking if the required variables to connect to Bitwarden are set.
Required variables are available.
Extracted secrets from Bitwarden and substituted them in the relevant files.
[Compute a9265aeffb3cc4f94a9f7138a8ef389e-ffc1c735f0a0b5bc-elb-us-east-1-amazonaws-com]:
- Installing shared manifests... 
namespace/tekton-results configured
secret/tekton-results-database unchanged
- Installing applications via Openshift GitOps... 
application.argoproj.io/pipeline-service unchanged
- Checking …
```
=> PLNSRVCE-730: [M9]Migrate infra credentials to Bitwarden

operator/images/access-setup/content/bin/setup_kcp.sh
Removed the generation of environment/kcp/workspace-controller/overlays/workspace.yaml which was unused
=> fix access-setup/setup_kcp.sh

developer/images/devenv/Dockerfile, operator/images/cluster-setup/Dockerfile, operator/images/cluster-setup/content/bin/install.sh, shared/hack/install.sh
During the image creation 'bw --version' was run as root while $HOME was already set to '/tmp/home'. This generated files in $HOME/.config owned by root, causing a failure when 'bw' was called again as a different user.
- The 'install_bitwarden' function has been cleaned up.
- The Dockerfiles for 'cluster-setup' and 'devenv' have been modified so that $HOME is set after all dependencies installation.
- Add missing yq dependency to cluster-setup
- Fix issue when the workspace is read-only for the user.
- Fix issue with tracing being activated in the middle of the install.
- Fix credential leak
=> Fix bitwarden installation

operator/images/cluster-setup/content/bin/install.sh
- Moving files into /tmp folder and assigning that as the workspace path is causing issues in the Gitlab CI.
- Corresponding PR has already been raised on Gitlab with more details.
=> Removing tmp folder in install.sh as its breaking deployment on staging cluster

operator/images/cluster-setup/content/bin/install.sh, operator/images/cluster-setup/content/bin/utils.sh
bitwarden fetch was moved to utils.sh:
- As a helper function it makes more sense to be in a generic script.
- It makes it easier to reuse it when debugging: for example we can do the following:
`source ./operator/images/cluster-setup/content/bin/utils.sh `
````fetch_bitwarden_secrets ````
=> Move bitwarden function to utils.sh

.tekton/pipeline-service-ckcp-testing.yaml
This PR improved the CI process
1. Added retry to ensure the whole ckcp test won't often fail due to the OCP clsuter intermitten issue
2. Added a few debug information when the ckcp test fail
=> added debug information when ckcp task fail

operator/gitops/compute/pipeline-service-manager/role.yaml
- minimizing use of wildcard characters
- defining verbs a/c to specific need of the privileges on a resource under APIGroup.
Note: The redefined role for pipeline-service-manager is based on the privileges required by it to create the kcp-syncer generated manifests. 
Closes #213 
=> PLNSRVCE-812 : Defining RBAC manifest a/c to RBAC best practices-

operator/gitops/argocd/tekton-chains/base/chains-controller-deployment.yaml, operator/gitops/argocd/tekton-results/deployment.yaml
With this PR, we add more configurations to deployment manifests to follow operator security standards.
- define SCC
- drop all capabilities
- run as non-root user
- resource requests and limits
- readOnlyRootFileSystem
=> PLNSRVCE-812 : define Pod and container securityContext and SCCs

operator/gitops/compute/pipeline-service-manager/role.yaml
=> fix typo in resource name while defining role for `pipeline-service-manager`

DEPENDENCIES.md, developer/images/devenv/Dockerfile, shared/config/dependencies.sh, shared/hack/install.sh
- Add checkov, shellcheck, yamllint to the documented dependencies
- Add checkov to install.sh
- Uses multi-stage builds for grpc-cli
=> Improve dependencies management

.tekton/pipeline-service-test.yaml
This PR is to fix the pipeline-service setup task in the CI.   The both values of `git_url` and `git_ref` are hardcoded in `developer/config.yaml`. `dev_setup.sh` needs to load the both values from `developer/config.yaml`, so it cannot set up pipeline-service with correct manifest. This fix updates  the values of both `git_url` and `git_ref` in file `developer/config.yaml` before executing `dev_setup.sh` script.
=> fixing the pipeline-service setup task in the CI

developer/images/devenv/Dockerfile, shared/config/dependencies.sh
An update in one of checkov's dependencies broke the install. Upgrading to a newer version is required to solve the problem.
=> Fix build of devenv failing on checkov

.tekton/pipeline-service-test.yaml, ci/images/quay-upload/Dockerfile, ci/images/vulnerability-scan/Dockerfile, operator/images/access-setup/Dockerfile, operator/images/cluster-setup/Dockerfile, operator/images/update-pipeline-service/Dockerfile, operator/test/test.sh
This fixes a vulnerability on python-pip introduced by the git package.
=> Upgrade base images from ubi8 to ubi9

operator/gitops/argocd/pipeline-service/tekton-results/deployment.yaml
In 3a11d3a91f runAsUser fields were removed, but one last field remained. Removing it here.
=> Remove a remaining runAsUser field

operator/test/manifests/test/tekton-chains/simple-copy-pipeline.yaml, operator/test/test.sh
Fix broken tekton-chains test   
- use Skopeo instead of Buildah in the Pipeline example manifest to copy image.
- remove checks for argo tekton-chains app since it's no more deployed as an argo-app.
Do a `KUBECONFIG=~/.kube/config CASES=chains ./operator/test/test.sh` once Pipeline-Service is deployed on the cluster.
=> Fix broken tekton-chains test

developer/openshift/dev_setup.sh, operator/images/access-setup/content/bin/setup_work_dir.sh, operator/images/cluster-setup/content/bin/install.sh
- Cosmetic changes to developer/openshift/dev_setup.sh
- Add binary check to operator/images/access-setup/content/bin/setup_work_dir.sh
- Move ArgoCD installation check from operator/images/access-setup/content/bin/setup_work_dir.sh to operator/test/manifests/test/tekton-chains/simple-copy-pipeline.yaml
=> Miscellaneous fixes to deployment scripts

operator/gitops/argocd/pipeline-service/tekton-results/deployment.yaml, operator/gitops/argocd/pipeline-service/tekton-results/permissions.yaml
tekton-results-database-secret is now automatically created via an initcontainer instead of relying on a manual or scripted action for this secret.
=> Automatically create tekton-results-database-secret

.tekton/pipeline-service-test.yaml, ci/images/ci-runner/hack/bin/copy-plnsvc-code.sh, ci/images/ci-runner/hack/bin/create-ci-runner-container.sh, ci/images/ci-runner/hack/bin/deploy-cluster.sh, ci/images/ci-runner/hack/bin/destroy-cluster.sh, ci/images/ci-runner/hack/bin/destroy-clusters.sh, ci/images/ci-runner/hack/bin/run-plnsvc-setup.sh, ci/images/ci-runner/hack/bin/run-tests.sh, ci/images/ci-runner/hack/manifests/sidecar/pod.yaml, ci/images/ci-runner/hack/manifests/sidecar/pvc.yaml, ci/images/ci-runner/hack/sidecar/bin/plnsvc_setup.sh, ci/images/ci-runner/hack/sidecar/bin/plnsvc_test.sh
This change aims to make the pipeline yaml more readable by abstracting the logic in scripts, as well as being able to apply the CI to the content of those scripts.
=> Move pipeline-service-tests logic to shell scripts

ci/images/ci-runner/Dockerfile, ci/images/static-checks/content/config/checkov.yaml, developer/images/devenv/Dockerfile
fix `ckv_docker` errors reported by checkov  
- fix `ckv_docker_3` issues
- ignore `ckv_docker_2` issues reported for Healthcheck inside
Docker containers
=> PLNSRVCE-1000: fix `ckv_docker` errors reported by checkov

ci/images/ci-runner/Dockerfile, ci/images/static-checks/content/config/checkov.yaml, developer/images/devenv/Dockerfile
This reverts commit a0e6a1a409d9f690f993ca4c596b37f3f4ceb205.
Caused
```
+ podman run --rm --env COSIGN_PASSWORD=dIsmAfF3VRRMLtkU --volume /tmp/tmp.4MDvmF5mi3/credentials/manifests/compute/tekton-chains/tmp:/workspace:z --workdir /workspace --entrypoint /usr/bin/cosign quay.io/redhat-appstudio/appstudio-utils:eb94f28fe2d7c182f15e659d0fdb66f87b0b3b6b generate-key-pair
Error: crun: writing file `/proc/947/setgroups`: Operation not permitted: OCI permission denied
command terminated with exit code 126
```
=> Revert "fix `ckv_docker` errors reported by checkov"

operator/gitops/argocd/pipeline-service/tekton-chains/chains-controller-deployment.yaml
Resource limits of tekton-chains are not tailored to stonesoup staging cluster usage, making the controller OOMKilled. They have been removed for now until we set the correct numbers next.
=> Remove tekton-chains resource limits

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
Until tekton-results prunes the pipelines as soon as the logs have been stored, we need to be more aggressive in the pruning to prevent users running into PVCs quota issues.
=> Increase pruner frequency to every 2 minutes

ci/images/ci-runner/Dockerfile
This is required for the minio commit to pass the CI
=> Add rsync to ci-runner image

ci/images/ci-runner/Dockerfile
This is required for the minio commit to pass the CI, as it requires envsubst
=> Add gettext to ci-runner image

operator/gitops/argocd/pipeline-service/tekton-results/base/configmap.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/db-configmap.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/db-service.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/db-statefulset.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/deployment.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/kustomization.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/permissions.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/service-account.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/service.yaml
This reverts commit 5284a2ccd6a507eda6fa48fcaee6cda84c13a569. The commit broke the CI, and the issue is hard enough to fix that reverting the commit is necessary.
=> Revert "update tekton-results manifests and images"

developer/images/dependencies-update/Dockerfile
This PR is to fix an Dockerfile issue `cannot access '/opt/dependencies-update/bin/*.sh': No such file or directory`
Signed-off-by: Xin Jiang @xinredhat
=> fix a Dockerfile issue

ci/images/ci-runner/hack/sidecar/bin/plnsvc_setup.sh, developer/openshift/dev_setup.sh, developer/openshift/gitops/argocd/pipeline-service/openshift-pipelines/kustomization.yaml, developer/openshift/gitops/argocd/pipeline-service/pipelines-as-code/kustomization.yaml, developer/openshift/gitops/argocd/pipeline-service/tekton-chains/kustomization.yaml, developer/openshift/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml, operator/images/access-setup/content/bin/setup_work_dir.sh
Add an option to dev_setup.sh to deploy the current branch.
This option should make it easy to test the source branch in PRs.
Validation of the PR needs to happen in throw away PR #471.
=> Use source branch for ci

operator/gitops/argocd/pipeline-service/kustomization.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/clusterrole.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/deployment.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/kustomization.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/service.yaml
- This PR makes the necessary changes to deploy the custom metrics exporter for Pipeline Service into Pipeline Service.
- The exporter code lives here - https://github.com/openshift-pipelines/pipeline-service-exporter 
This PR goes along with https://github.com/redhat-appstudio/infra-deployments/pull/1304 on infra-deployments.
=> Adding custom exporter code to pipeline service

ci/images/ci-runner/hack/sidecar/bin/plnsvc_test.sh, operator/gitops/argocd/pipeline-service/tekton-chains/chains-secrets-config.yaml
This fixes an issues when deploying where the tekton-chains controller was failing because it did not have access to the secret.
=> Create signing-secret early in the deployment

operator/gitops/argocd/pipeline-service/metrics-exporter/clusterrolebinding.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/deployment.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/kustomization.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/serviceaccount.yaml
Local run:
```
[bnr@bnr pipeline-service]$ k -n openshift-pipelines get pods
NAME                                                 READY   STATUS        RESTARTS   AGE
pipeline-metrics-exporter-7c87c975bc-t2r5r           1/1     Running       0          33s
```
```
pipeline_service_exporter_build_info{branch="",goversion="go1.19.5",revision="",version=""} 1
pipelinerun_duration_completed_seconds{name="pipelinerun-echo-greetings",uid="da686962-80de-413e-8ee8-34987b60c0ac"} 10
pipelinerun_duration_scheduled_seconds{name="pipelinerun-echo-greetings",uid="da686962-80de-413e-8ee8-34987b60c0ac"} 0
```
=> Use custom service account for metrics deployment

ci/images/static-checks/content/config/checkov.yaml
fix CKV_DOCKER errors 
- ignore `developer` directory from Checkov scan
- ignore Healthcheck instruction error for docker images
=> fix CKV_DOCKER errors

operator/gitops/argocd/pipeline-service/tekton-chains/chains-secrets-config.yaml
This PR is required to fix the error that was found when trying to bootstrap stonesoup
```
Failed to pull image "registry.redhat.io/openshift4/ose-cli:v4.11": rpc error: code = Unknown desc = loading manifest for target platform: reading manifest sha256:836004f30587ffb184ee4681dd1c6d779e6703a18fd9a69b47c27f062fc28862 in registry.redhat.io/openshift4/ose-cli: unsupported: Not Found, or unsupported. V2 schema 1 manifest digest are no longer supported for image pulls. Use the equivalent schema 2 manifest digest instead. For more information see https://access.redhat.com/articles/6138332
```
The image version is based on a [fix that was merged recently](https://github.com/redhat-appstudio/build-definitions/pull/309/files) to fix build pipelines
Verified the stonesoup bootstrap with [the …
=> fix: bump chains-certs-configuration image version

.tekton/push.yaml
this will generate PRs to update 
- https://github.com/redhat-appstudio/infra-deployments/blob/main/components/pipeline-service/development/kustomization.yaml
- https://github.com/redhat-appstudio/infra-deployments/blob/main/components/pipeline-service/staging/base/kustomization.yaml
with the commit IDs of merged pipeline-service PRs.
Note: while staging is working off of `ref=appstudio-staging` this change will leave the staging defs in infra-deployments alone.  Once that has been updated to a sha ref, this will then start updating that.
@Roming22 @Mo3m3n FYI
Also, I will note here that I could not exactly copy/paste what the controllers in github.com/redhat-appstudio use for this, as they use appstudio to build their images as well
where as we are doing it with github actions per …
=> PLNSRVCE-1105: add pac push job to update pipeline-service sha refs in infra-deployments

operator/gitops/argocd/pipeline-service/metrics-exporter/deployment.yaml
This needs to be merged after https://github.com/openshift-pipelines/pipeline-service-exporter/pull/6 as the tag is the commit ID of that merge.
=> Update metrics exporter image tag and increase requests on the memory and CPU

developer/images/dependencies-update/hack/bin/tasks/update_binaries.sh, shared/config/dependencies.sh
The change also fixes a bug that was forcing the HyperShift version to be set with the hadolint version.
=> Add mechanism to freeze a dependency version

.tekton/pipeline-service-upgrade-test.yaml, ci/images/ci-runner/hack/bin/deploy-cluster.sh, operator/test/test.sh
This CI is used for testing  the upgrade upgrade. It first deploy pipeine-service on a branch new cluster .After that it applies the changes of the PR to deploy it on the same cluster.
Signed-off-by: Xin Jiang @xinredhat
=> PLNSRVCE-1111: CI: Test the upgrade path

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
- Setting the embedded-status to _minimal_ can significantly reduce the size of the PipelineRun's status object. This is important for large scale production environments where large number of PipelineRuns are expected to be generated.
- The default value set for this flag is _full_. This PR updates the tektonconfig to set the value to _minimal_.
=> Add a feature flag to set embedded status to minimal

operator/gitops/argocd/pipeline-service/metrics-exporter/clusterrolebinding.yaml
- The existing name seems to be conflicting with another name in the Stonesoup cluster. Hence, I am updating the 
ClusterRoleBinding name.
- This PR will be followed by a corresponding one on infra-deployments to make the same change.
=> Change the name of CRB for exporter

operator/gitops/argocd/pipeline-service/openshift-pipelines/openshift-operator.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
There's an urgent need to bring 1.9 to production to unblock various teams. This PR should unblock them.
=> Upgrade to openshift-pipelines 1.9

developer/openshift/gitops/argocd/pipeline-service-storage/minio/operator/allow-argocd-to-manage.yaml, developer/openshift/gitops/argocd/pipeline-service-storage/minio/operator/minio.yaml, developer/openshift/gitops/argocd/pipeline-service-storage/minio/tenant/tenant.yaml
When pipeline-service is imported in infra-deployments project (as kustomize overlays and not argcd app), the sync-wave params on minio makes introduces a kind of dead lock. That is tekton-results waiting for its storage backend and minio waiting for the first sync-wave to finish. This has been fixed by removing the sync-wave which should still let minio deploy correctly
=> Remove argocd sync-wave param from minio

operator/gitops/argocd/pipeline-service/pipelines-as-code/kustomization.yaml
- Locally tested ✔️     
- It should also unblock @bnallapeta's PR - https://github.com/redhat-appstudio/infra-deployments/pull/1436
=> downgrade pac to 0.16

developer/local/kind/ingress-router-us-east1.yaml, developer/local/kind/ingress-router-us-west1.yaml
registry.k8s.io replaces k8s.gcr.io. Announcement: https://kubernetes.io/blog/2023/03/10/image-registry-redirect/
=> Update image registry link

operator/images/cluster-setup/content/bin/utils.sh
This is to fix the issue of [PLNSRVCE-1267](https://issues.redhat.com/browse/PLNSRVCE-1267) , the root cause is that Deployment tekton-results-api needs more time to be ready
=> Extended wait time for deployments/tekton-results-api to be ready

operator/gitops/argocd/pipeline-service/tekton-results/base/api-route.yaml
Use HSTS header for tekton-results api route. This option should include HSTS (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) header to response.
=> Use HSTS header for tekton-results api route.

operator/gitops/argocd/pipeline-service/metrics-exporter/deployment.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/kustomization.yaml
- Provides an option to set image name and tag in the kustomization.yaml
- Sets default tag to main in the deployment.yaml as a placeholder. When pipeline service is deployed, kustomization would override with the tag in the file.
- Update metrics-exporter kustomization to use images built from RHTAP
=> Update metrics-exporter kustomization to use images built from RHTAP

.tekton/pipeline/acceptance-tests.yaml, .tekton/pipeline/upgrade-tests.yaml, ci/images/ci-runner/hack/bin/destroy-clusters.sh
**Changes:**
1. When one of CI tasks fail, such as `plnsvc-setup` , CI won't destroy the cluster
2. The cluster will be kept alive for around 2 hours, when it exceeds  2 hours, it probably will be destroyed automatically
=> PLNSRVCE-1268: change to allow cluster alive for 2 hours when CI task fail

operator/gitops/compute/pipeline-service-manager/role.yaml
Unfortunately the logs have already been pruned in CI, but during the failed run https://console-openshift-console.apps.pipeline-stage.3jhu.p1.openshiftapps.com/k8s/ns/pipeline-service-ci/tekton.dev~v1beta1~PipelineRun/pipeline-service-test-fc4kx/logs/plnsvc-setup
I got a permission error stating that the `placement-service-manager` SA could not get pod logs while running https://github.com/openshift-pipelines/pipeline-service/blob/2e84c5ef368b605ef99e4b9ba70972daeee73b39/operator/images/cluster-setup/content/bin/utils.sh#L46
=> allow placement-service-manager to dump pods, pods/logs

operator/gitops/compute/pipeline-service-manager/role.yaml
This permission is required when installing the cluster with dev_setup.sh
=> Allow pipeline-service-manager to view subscriptions

operator/gitops/argocd/pipeline-service/tekton-results/base/api-migrator-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/kustomization.yaml
Add patches to migrator database config to transform DB secret key values.
Causing error in pod creation:
container "migrator" in pod "tekton-results-api-5fd5f67554-4vkvz" is waiting to start: CreateContainerConfigError
=> Migrator config patches

developer/hack/run_image.sh, developer/images/devenv/Dockerfile
* Fix missing rsync dependency
* Enable podman in podman to run the image creating the tekton-chains certs
* Mount user's config directories for ssh and kubernetes to enable github and kubernetes
=> Fix devenv

.tekton/pipeline-service-static-code-analysis.yaml, ci/images/static-checks/content/bin/checkov.sh, ci/images/static-checks/content/config/checkov.yaml, operator/test/test.sh
1) openshift pod security / security context contraints ultimately mutates pods on their creation from deployments, etc. and fools the generic k8s `checkov` scans; this PR adds skips on the scans directly mutated 
2) a few miscellaneous skips were also added based on analysis
based on how things go, and if we can get to an acceptable baseline, we can set `soft-fail` to false, and in theory have PR checks fail if upstream changes lead to security violations we are not happy with
3) added some bash to verify that all are pods are running with the restricted SCC, which effectively replaces specific checks from `checkov` that we are now skipping
=> PLNSRVCE-1152: update checkov static checks; turn off checkov soft fail; add openshift scc/hostnetwork tests

.tekton/pipeline/acceptance-tests.yaml, .tekton/pipeline/upgrade-tests.yaml, .tekton/tasks/destroy-cluster.yaml, ci/docs/continuous_integation.md, ci/images/ci-runner/hack/bin/destroy-cluster.sh, ci/images/ci-runner/hack/bin/run-plnsvc-setup.sh, ci/images/ci-runner/hack/bin/run-tests.sh
To prevent too many resources from being consumed, keeping the cluster is not the default action.
If a developer wants to investigate, they need to connect to a pod and remove the 'destroy_cluster.txt' file located at the root of the source directory.
=> Destroy CI clusters when there is no active investigation

operator/gitops/argocd/pipeline-service/tekton-results/base/kustomization.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/watcher-logging.yaml
During debugging the issues bumping results to `downstream-0.5.0-02` I discovered you could not use https://github.com/openshift-pipelines/tektoncd-results/blob/downstream-0.5.0-02/config/base/env/config to bump the logging levels for the watcher pod.  Those only changed the log level in the api server.
There appear to be valid reasons why that env var based approach is not enabled for the watcher when you look at the code, and the doc explicitly steers one to use the knative based config map approach.
So to reconcile with our use of gitops, I'm exposing manipulation of the requisite fields here.
I have successfully tested this using https://github.com/openshift-pipelines/pipeline-service/blob/main/developer/config.yaml and presumably it should work then with `--use-current-branch` as …
=> allow for watcher logging level customization via gitops

operator/gitops/compute/pipeline-service-manager/role.yaml, operator/images/access-setup/content/bin/setup_work_dir.sh, operator/images/cluster-setup/content/bin/install.sh, operator/images/cluster-setup/content/bin/utils.sh
OK this addresses and issue that @scoheb first reported to us when doing an upgrade on his long running cluster, where @AndrienkoAleksandr and I did enough debug that we saw the `minio-storage-configuration` and `` secrets had mismatched S3 passwords, leading to the result api server's `mc` init container complaining about such a mismatch, followed by @adambkaplan saying he same something similar, and then finally, something @sayan-biswas and I have seen pretty consistently this show up when debug attempt to bump the version of downstream results in this repo.
Bottom line, multiple calls to the password generation in via `openssl rand ..` lead to regeneration of the password.  That coupled with gitops/kustomize concurrency, lead to intermittent to fairly consistent mismatches.
The …
=> PLNSRVCE-1292: only create tekton-results-manifests once in CI tests (especially upgrade test)

operator/gitops/argocd/pipeline-service/pipelines-as-code/kustomization.yaml
Workaround for SRVKP-3064.
This is acceptable because we do not require the latest PaC version at the moment.
=> Downgrade PaC image to 1.9.2-1

operator/gitops/argocd/pipeline-service/tekton-results/base/watcher-logging.yaml
- a previous PR removed the zap-logger-config data, because in config map
patches, data is replaced and not patched, refer #616
- add missing data to zap-logger-config
- update zap-logging-config according to ADR 6
- Refer PLNSRVCE-1308
=>  Retain zap logging config for tekton results

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml, operator/test/manifests/setup/pipeline-service/appstudio-pipeline-service-account.yaml, operator/test/manifests/setup/pipeline-service/kustomization.yaml, operator/test/manifests/setup/pipeline-service/namespace.yaml, operator/test/manifests/test/tekton-chains/chains-test-service-account.yaml, operator/test/test.sh
The pipeline service account permissions are too open by default. Therefore the account needs to be replaced with an account with more limited permissions.
The service account is managed by the DevSandbox team.
=> Change default SA for Pipelines to appstudio-pipeline

operator/gitops/argocd/pipeline-service/pipelines-as-code/kustomization.yaml, operator/gitops/argocd/pipeline-service/tekton-chains/kustomization.yaml
**This commit should only be merged by @gabemontero or @Roming22**
This reverts commit 04a0df2558ebb6879c2a413fc4f7d1ade53f5d6f.
This is a workaround in case we're still having issues with the AppStudio e2e tests at the end of the day.
=> Revert "Use downstream images for pipelines-as-code and tekton-chains"

operator/gitops/argocd/pipeline-service/tekton-chains/chains-secrets-config.yaml
It was possible for the tekton-chains-trusted-cabundle job to run before the config-trusted-cabundle was cleaned by the OSP operator
=> Fix possible race issue

operator/gitops/argocd/pipeline-service/openshift-pipelines/config-logging.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/kustomization.yaml
align Pipelines Controller logs with ADR-6    
- add config-logging to patch default configmap used for setting zap encoder.
=> Align Pipelines Controller logs with ADR-6

operator/gitops/argocd/pipeline-service/openshift-pipelines/appstudio-pipelines-scc.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/kustomization.yaml
The name is conflicting with the SCC created by OSP, and triggered the RHTAPBUGS-304 issue.
=> Rename pipelines-scc to appstudio-pipelines-scc

operator/gitops/README.md, operator/gitops/argocd/grafana/dashboard.yaml, operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json, operator/gitops/argocd/grafana/kustomization.yaml
A Grafana dashboard will make it easy for operators to monitor Pipeline Service components at a glance. The dashboard definitions here can be deployed using Kustomize on a cluster with the Grafana operator installed.
This contains an initial dashboard definition, with the intent that future contributors can add additional graphs and charts. The dashboard consists of the following:
- Line graphs of completed TaskRuns and PipelineRuns, expressed as a rate per hour.
- A success gauge measuring the percent of successful TaskRuns and PipelineRuns.
The dashboard assumes that Prometheus will be used as the data source, and that the following metrics are recorded and exported via a ServiceMonitor:
- `tekton_pipelines_controller_pipelinerun_count`
- `tekton_pipelines_controller_taskrun_count`
=> Add Initial Pipeline Serivce Dashboard

operator/gitops/argocd/pipeline-service/pipelines-as-code/kustomization.yaml
As we are working through issues to migrate to the downstream images, the PaC version has been left
unchanged.
There has been quite a few bug fixes that have
been delivered that would improve the UX of
RHTAP, therefore an update seems warranted.
The version has been chosen to be compatible with
OSP 1.10, so as not to impact the image migration.
=> Upgrade PaC version to 0.17.3

operator/gitops/argocd/pipeline-service/tekton-chains/chains-controller-deployment.yaml, operator/gitops/argocd/pipeline-service/tekton-chains/chains-secrets-config.yaml
The chains-ca-cert ConfigMap was introduced in order to allow the Tekton Chains controller to push content to the integrated OpenShift registry. Since then, we have moved away from using this registry altogether in favor of quay.io.
This change removes usage of the chains-ca-cert ConfigMap as well as the ArgoCD Jobs responsible for setting it up.
https://github.com/openshift-pipelines/pipeline-service/pull/673
=> Remove usage of chains-ca-cert

operator/gitops/argocd/pipeline-service/metrics-exporter/deployment.yaml
Have pattern where the exporter in production hovers around 256 MiB for several hours, and when we bump up too much against it, the kubelet restarts us.  No error message in prev log.  So consistent with mem limit rebump.
Going to 512 to start.
As point of ref, tekton pipeline controller in production is hovering around 1GiB (and it has no mem limit).
We watch less that ^^ so let's see the 512 run first.
=> PLNSRVCE-1310: bump exporter mem from 256 to 512 Mib

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
- container_cpu_usage_seconds_total is the counter of cpu usage. 
The "sum of rate" gives us the average vCPU usage over the past 5 minutes.
- container_memory_working_set is the gauge metric of memory used,.
and is what the kubelet uses to determine OOM kills.
=> Grafana Observational graphs for Pipelines Controller Resource Utilization

.tekton/pipeline/acceptance-tests.yaml, .tekton/pipeline/stonesoup-integeration-tests.yaml, .tekton/pipeline/upgrade-tests.yaml, .tekton/tasks/destroy-cluster.yaml, ci/images/ci-runner/hack/bin/create-ci-runner-container.sh, ci/images/ci-runner/hack/bin/destroy-cluster.sh, ci/images/ci-runner/hack/sidecar/bin/plnsvc_test.sh
* Improve task naming consistency
* Fix issue with KUBECONFIG not being output in case of error
* Output KUBECONFIG early in the process to allow real time investigations
* Fix an issue that would trigger the tests to fail if the user deleted the destroy-cluster.txt before the tests finished
=> Improve CI investigation

operator/gitops/argocd/pipeline-service/metrics-exporter/deployment.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/kustomization.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/servicemonitor.yaml
These are the changes I needed to get the pipeline-service-exporter metrics to be visible from the grafana dashboards.
Turns out we need to move the servicemonitor def from infra-deployments to this repo
A couple of minor selector labeling tweaks on top.
=> PLNSRVCE-1069:  get exporter metrics to work from dashboards

developer/openshift/dev_setup.sh, developer/openshift/gitops/argocd/kustomization.yaml, developer/openshift/gitops/argocd/pipeline-service-o11y.yaml, developer/openshift/gitops/argocd/pipeline-service-o11y/README.md, developer/openshift/gitops/argocd/pipeline-service-o11y/appstudio-grafana/allow-argocd-to-manage.yaml, developer/openshift/gitops/argocd/pipeline-service-o11y/appstudio-grafana/kustomization.yaml, developer/openshift/gitops/argocd/pipeline-service-o11y/appstudio-grafana/namespace.yaml, developer/openshift/gitops/argocd/pipeline-service-o11y/appstudio-prometheus/allow-argocd-to-manage.yaml, developer/openshift/gitops/argocd/pipeline-service-o11y/appstudio-prometheus/kustomization.yaml, developer/openshift/gitops/argocd/pipeline-service-o11y/kustomization.yaml
Enhance our dev setup flow by allowing developers to do "Gitops Inner Loop" development with Prometheus and Grafana. This is provided by an ArgoCD application that deploys a slimmed down version of the App Studio Prometheus and Grafana observability stacks. The dashboards for Pipeline Service are referenced "in-tree", which allows team members to iterate via GitOps (per our usual development flow).
=> Inner Loop Observability with Prometheus and Grafana

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
* tekton_pipelines_controller_running_pipelineruns_count -
Number of pipelineruns executing currently
* tekton_pipelines_controller_running_taskruns_count -
Number of taskruns executing currentl
* tekton_pipelines_controller_taskruns_pod_latency
Scheduling latency for the taskruns pods
* tekton_pipelines_controller_workqueue_depth -
The workqueue for the Tekton Pipelines controller
* Pipelines controller restarts
* tekton_pipelines_controller_client_resutls -
Total number of K8s API requests made by Pipelines Client
=> Grafana Observational graphs for Pipelines Controller Monitoring

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
The following metrics are being queried:-
* pipelinerun_duration_scheduled_seconds
Using the expr - `sum by (namespace) ((avg_over_time(pipelinerun_duration_scheduled_seconds_sum[1h]) / avg_over_time(pipelinerun_duration_scheduled_seconds_count[1h])))`
We calculate average scheduling duration per PipelineRun in seconds for each namespace over the last 1 hour
* tekton_pipelines_controller_pipelinerun_duration_seconds
Using the epxr - `sum by (namespace) ((avg_over_time(tekton_pipelines_controller_pipelinerun_duration_seconds_sum{status=\"success\"}[1h]) / avg_over_time(tekton_pipelines_controller_pipelinerun_duration_seconds_count{status=\"success\"}[1h])))`
We calculate average duration of successful pipelineruns in seconds over one hour time window grouped by namespace.
=> Pipeline Service troubleshooting Grafana Dashboard

operator/gitops/argocd/pipeline-service/tekton-chains/chains-config.yaml
https://issues.redhat.com/browse/HACBS-2209
RHTAP is only concerned with PipelineRun attestations. The TaskRun attestations add noise and potential confusion to users. Also, the PipelineRun attestation already contains all the data found on the TaskRun attestation.
=> Stop producing TaskRun attestations

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
For metrics exporter observation/health, I've got 3 panels
- cpu similar to what @ramessesii2 did for pipeline controller
- mem similar to what @ramessesii2 did for pipeline controller
- workqueue depth, though it is different from the tekton controllers because the exporter is controller-runtime based, not knative based 
fortunately @adambkaplan 's inner loop dev starting working for me after a few days of grafana not coming up :-) ... it made things much easier / safer than manipulating staging dashboards
Screenshot attached
=> PLNSRVCE-1336: add metrics exporter observational/health graphs

operator/gitops/argocd/pipeline-service/openshift-pipelines/config-pac.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/kustomization.yaml
As part of getting the 1.11 bump working into staging, I discovered that the patch of the `pipelines-as-code` configmap at https://github.com/redhat-appstudio/infra-deployments/blob/main/components/pipeline-service/staging/base/kustomization.yaml#L23-L27 and https://github.com/redhat-appstudio/infra-deployments/blob/main/components/pipeline-service/staging/base/pac-app-name.yaml was not taking hold.
As @Michkov made me realize, we cannot do a gitops patch of an object if gitops did not create the object.
This is not happening with the 1.11 bump as we have openshift pipelines operator creating pac vs. the pipeline service gitops based deploy of pac from the upstream release.
This change now creates the config map as part of our gitops tree (similar to what we are doing with the logging …
=> PLNSRVCE-1350: add pipelines-as-code configmap to gitops tree to allow RHTAP to gitopos patch

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
1. tekton_pipelines_controller_running_taskruns_throttled_by_quota_count - 
Number of taskruns executing currently, but whose underlying Pods or Containers are suspended by k8s because of defined ResourceQuotas. Such suspensions can occur as part of initial scheduling of the Pod, or scheduling of any of the subsequent Container(s) in the Pod after the first Container is started
3. tekton_pipelines_controller_running_taskruns_throttled_by_node_count - 
Number of taskruns executing currently, but whose underlying Pods or Containers are suspended by k8s because of Node level constraints. Such suspensions can occur as part of initial scheduling of the Pod, or scheduling of any of the subsequent Container(s) in the Pod after the first Container is started.
=> add Takruns Throttling metrics to Pipelines Grafana Dashboard

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
* Add `container=""` to the relevant queries which makes sure that we only watch main containers.
* Cosmetic changes to the graphs
=> fix Grafana queries for resource utilization

.tekton/pipeline-service-test.yaml, .tekton/pipeline-service-upgrade-test.yaml, .tekton/pipeline/acceptance-tests.yaml, .tekton/pipeline/stonesoup-integeration-tests.yaml, .tekton/pipeline/upgrade-tests.yaml
Increase the timeout limit for PipelineRuns to avoid CI timeout failure. The main reason is that ROSA Hypershift creation/deletion is not stable, sometimes they need longer time than 15 mins we expected.
=> Increased pipeline timeout

developer/openshift/gitops/argocd/pipeline-service-o11y/appstudio-grafana/kustomization.yaml, operator/gitops/argocd/grafana/dashboard.yaml
As part of this bug fix and the upgrade to `GrafanaOperator` v5, we have to update the `GrafanaDashboard` resource to match the new api
More details:
https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1690371680784569
The dashboard is still presenting data due to a patch we merged to RHTAP, and it will be removed after these changes will be merged
=> fix(RHTAPWATCH-8): Update GrafanaDashboard to match GrafanaOperator v5

developer/openshift/dev_setup.sh, operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json, operator/gitops/argocd/pipeline-service/tekton-results/api-metrics-service.yaml, operator/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml, operator/gitops/argocd/pipeline-service/tekton-results/service-monitor.yaml, operator/test/test.sh
This is a workaround for the bug [PLNSRVCE-1210](https://issues.redhat.com/browse/PLNSRVCE-1210)
This error is appearing in the API service logs because when we are creating a route in an Openshift cluster with HTTP2 enabled, HAPROXY opens  TCP connection to that route for health check, and maybe closes the connection before the handshake is complete. The `net` golang package logs these requests.
But I have observed that these issue doesn't happen if we separate the ports in different service (not sure why this behaviour)
=> Fix HTTP2 error with openshift routes

.tekton/pipeline/update-repository.yaml, .tekton/tasks/update-repository.yaml, .tekton/update-dependencies.yaml
* Use pipelineRef and taskRef
* Start work to make the task generic enough so it can be submitted to redhat-appstudio/build-definitions
Note that the Task is currently incomplete as it does not push the changes made by the script back to the repository.
=> Refactor update-dependencies 1/2

.tekton/pipeline/update-repository.yaml, .tekton/tasks/update-repository.yaml, .tekton/update-dependencies.yaml
This PR simplifies the push to GitHub by using the token properly. 
Because of issues pushing to the repository, I initially thought that I would need to send the changes through the GitHub API. This would have required the detailed information I was logging in `.commits.json`.
Since I've now managed to perform a `git push` to the repository, the task can be greatly simplified.
=> Use pac-gitauth secret for push

developer/images/devenv/Dockerfile, operator/test/manifests/test/tekton-chains/simple-copy-pipeline.yaml
We were using the v4.5.1 tag and it's been replaced by v4.6.1. Those both are floating tags and not static ones, so it does not make much difference if we start using a bit more generic one v4.6 while still preserving the versions of the extra rpms installed. Same happened with the skopeo image, replaced with the new one.
=> Fix podman image tag used in CI

developer/openshift/reset.sh, operator/test/test.sh
With PaC being installed by the OSP operator, we no longer need the pipelines-as-code namespace. Here we cleanup references to that namespace from the reset and test scripts.
=> Remove refs to PaC namespace

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json, operator/gitops/argocd/pipeline-service/openshift-pipelines/chains-observability-service.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/chains-service-monitor.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/kustomization.yaml
- fix tekton chains servicemonitor issue
- remove tekton chains patches
- add grafana dashboard with two metrics
- refer PLNSRVCE-1332
**Chains currently does not have any useful metrics**
=> add tekton chains grafana dashboard

operator/gitops/argocd/pipeline-service/openshift-pipelines/chains-secrets-config.yaml, operator/test/manifests/test/tekton-chains/public-key.yaml, operator/test/test.sh
* Cosign by default creates immutable secrets, so we need delete
permissions in openshift-pipelines namespace over secrets
https://github.com/sigstore/cosign/blob/main/pkg/cosign/kubernetes/secret.go#L119C5-L119C14
* additional check to make sure public key is not empty.
=> [DNM] fix chains signing-secrets public-key access

operator/gitops/argocd/pipeline-service/openshift-pipelines/chains-secrets-config.yaml, operator/test/test.sh
@gabemontero @ramessesii2 I've noticed that in our environments the secrets are not immutable. That's because they were created through a different process than we use know.
I've modified the job so it transforms mutable secrets into immutable secrets, which will help with configuration drift.
This PR should be merged after #776.
=> Make the tekton-chains signing-secrets immutable

operator/gitops/argocd/pipeline-service/openshift-pipelines/chains-secrets-config.yaml
This will ensure that any failure to setup the secret is properly reported in the job status.
=> Add errexit,nounset,pipefail to chains-secrets-config job

developer/openshift/gitops/argocd/pipeline-service-o11y/README.md, operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
In comparing with other RHTAP components whose grafana dashboards were working, none of them had the datasource/uid pattern in their JSON in the repos.  However, when I examined their JSON live, I saw example of this.
I suspect that when the last update to our dashboard was made, it pulled in live data like this datasource/uid pairing, and what we had was now stale.
Here is a screen shot of a RHTAP bootstrap against my local cluster using my pipeline service branch for this PR:
@Roming22 @enarha @avinal @sayan-biswas @ramessesii2 @prietyc123 FYI since all of you along with me have touched this dashboard at one time or another.
=> PLNSRVCE-1467: fix missing datasorce error in stage/prod pipeline-service grafana dashboard

developer/openshift/gitops/argocd/pipeline-service-o11y/README.md, operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
- this change adds a panel for alerts, and then adds the query we use for our SLO scheduling alert, setting the threshold to match our initial SLO overhead percentage, 3%
- also updated the developer instructions to explain how to export without including the datasource uid's set during local testing
I also renamed the "overview" panel to something more specific (i.e rates)
I also collapsed by default all the other rows/sections for now
Screenshot:
=> PLNSRVCE-1469: add row/panel for scheduling alert

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
by the way now that I know what to do here @openshift-pipelines/pipelines-service I found other examples of this setting in our dashboard file here
=> PLNSRVCE-1469: print 'No data' when the scheduling alert query has no data

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
=> fix pipeline execution overhead alert query

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
This commit brings panels that display the various merics recently added to the exporter that measure various phases of a PipelineRuns execution, and renames "troubleshooting" to "performance analysis":
- rename troubleshooting row and change threshold of successful pipelinerun from 80 to 600
- add pipelinerun pod duration bargraph to analysis row
- add kubelet mark schedulable bargraph to analysis row
- add kubelet pulling images and start container bargraph to analysis row
- rename avg sched duration to more precise learn of create duration
- add pipelinerun pod avg duration by task, namespace bargraph to analysis row
- move throttled by quota chart to analysis row
- move throttled by node chart to analysis row
- move throttled by quota to the left
- add throttled by pvc graph to …
=> add various performance diagnostic metrics to dashboard; fix alert panels not rendering by default

ci/images/ci-runner/hack/bin/destroy-cluster.sh
destroy-cluster.sh will exit after sending the request for deletion to speed up the pipeline.
=> Optimizing the process of ROSA destroying

developer/openshift/gitops/argocd/pipeline-service/tekton-results/minio-create-bucket.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/deployment.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/chains-secrets-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-kube-rbac-proxy.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-migrator-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-s3-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-kube-rbac-proxy.yaml
* run containers as non root
* run containers with read only root file system
The 'mc' init container is using the /tmp folder so for that container, mount an empty dir volume to /tmp to be able to set root file system readonly while being able to write to /tmp.
PLNSRVCE-1476
=> Fix kube-linter issues

developer/images/devenv/Dockerfile
It reported error `Error: Unable to find a match: python3-devel-3.11.5` when building devenv image. It needs to install `python3-devel-3.11.6` as replacement.
=> Fix a minor error of devenv image

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
Restore a setting that was mistakenly removed with commit b2626be4fc649b5184b8bf3e661bbc46319c884b
which break the deployment of the application
=> Fix TektonConfig

developer/openshift/gitops/argocd/pipeline-service/tekton-results/minio-create-bucket.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-migrator-config.yaml
Init containers are harder to figure out the required resources as they do not run long enough to have metrics collected. Both container worked with 5m/32Mi in a dev environment. Put the limits higher to make sure they works in production environment even though the nature of the work done by both should not differ much from dev to production environment.
PLNSRVCE-1476
=> Set Set cpu/memory requests/limits for tekton-results-api init containers

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
The tekton result pruner is not deleting all PLRs after completion because of a safeguard mechanism when PLR have an ownerRef.
This change restores the pruner to handle those resources.
=> Enable OSP pruner

operator/gitops/argocd/pipeline-service/tekton-results/api-s3-config.yaml
This container is similar resources consumption wise on low and high traffic instances at rest:
```
oc adm top pod tekton-results-api-6bcb5d967-wspvm --containers
POD                                  NAME    CPU(cores)   MEMORY(bytes)
tekton-results-api-6bcb5d967-wspvm   api     1m           39Mi
```
```
oc adm top pod tekton-results-api-7bff76858f-thgrf --containers
POD                                   NAME   CPU(cores)   MEMORY(bytes)
tekton-results-api-7bff76858f-thgrf   api    2m           64Mi
```
It does has peak around 340Mi on high traffic instances.
PLNSRVCE-1476
=> Set cpu/memory requests/limits for tekton-results-api/api

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
Noticed this while I was working on the gitlab app-sre SLO/SLI docs
=> fix missing millisecond to second conversion in grafana dashboard execute overhead query

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
During unsuccessful attempts to get our alert queries running on the app-sre grafana dashboard, I did come up with a simpler query which reaches the same basic effect of only using the last 30 minutes of data available.  This change will also work better with the use of range seen in other successful app-sre dashboard queries.
Also, I realized an earlier change by me  to divide our milliscecond metric's _count by 1000 was incorrect.  Only the _sum has actual millisecond based observations that need to be converted (as was originally done).
The PR where I incorrectly changed what @ramessesii2 had for converting milliseconds to seconds was https://github.com/openshift-pipelines/pipeline-service/pull/835
Here is a screen shot of how the new queries look in RHTAP red-hat prod:
=> optimize alert query; revert incorrect millisecond to second conversion fix

ci/images/static-checks/content/config/checkov.yaml
The --skip-fixes flag has been deprecated in v3.x.
=> Update checkov configuration

.tekton/test-docker-images-build.yaml, developer/hack/build-images-buildah.sh
As the images are not used on the cluster, deleting them helps with resource management.
=> Add option to delete images after building them

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
During some recent monitoring of the alert panels in stage and prod, a rash of pipelinerun errors lead to some abnormally high levels for the schedule overhead alert as compared to the execution overhead alert.  This was the motivation to add the status label to the schedule metric like we already have on the other ones.  This change now leverages that label in the grafana dashboard.
=> update scheduled alert panel to only use successful pipelineruns with scheduled metric

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
Figured out via temporary edits to the appstudio dashboards that our alert panels the threshold switch in color from green to red will only occur if the mode is percentage vs. absolute
=> fix threshold color for 2 alert panels

.github/workflows/build-push-images.yaml, .github/workflows/individual-image-scanner-quay.yaml, .github/workflows/periodic-scanner-quay.yaml
This should get rid of the 'actions uses node12 which is deprecated' warning.
=> Bump github action/checkout version

operator/gitops/argocd/pipeline-service/metrics-exporter/deployment.yaml
This way, we can just append args in infra-deployments if we want to add new ones, but conversely we will not replace any future args we add in pipeline-service
=> add empty args for safer patching in infra-deployments

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
During the review of the alert rule definitions in redhat-appstudio/o11y we learned that 'increase' is a bit better for us vs. 'sum_over_time' because it better deals with metric controller restarts.  Adjusting our appstudio panels accordingly.  Live comparisons on the RHTAP clusters have proven favorable.
=> adjust grafana alert panels to match where o11y alerts landed

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
Tracking of our grafana alert panels uncovered a form of "unfair inflation" of our overhead percentages, given
- the tekton timestamps are rounded to seconds
- certain user defined pipelines could succeed very quickly, in a manner of seconds, which is much much faster than RHTAP pipelines
So we built single metrics for our two overheads which combine algorithms from the multipe metrics we were using before, but also ignored pipelines which ended very quickly.
After monitoring for a few weeks, the results appear favorable, with these specifics:
- if the super fast pipelines had 0 overhead (i.e. 0 to 459 milliseconds), then when the ovehead over time was small with the original metrics that included every pipelinerun, our filtered metric was slightly higher because they did not benefit from …
=> switch overhead alert panels to filtered metric

.tekton/open-infra-deployment-pr.yaml
The pipeline-service application is now updated via deploy file after pr: https://github.com/redhat-appstudio/infra-deployments/pull/2383
So adding the kustomize output in the infra-deployment-update-script so that the bot also update the deploy file for staging folder of pipeline-service
=> build the kustomize output to Infra-deployment deploy file

operator/gitops/argocd/pipeline-service/tekton-results/watcher-config.yaml
This container does not take much resources on low traffic instances such as a dev environment:
```
oc adm top pod tekton-results-watcher-6594cbf977-xwf6c --containers
POD                                       NAME      CPU(cores)   MEMORY(bytes)
tekton-results-watcher-6594cbf977-xwf6c   watcher   0m           37Mi
```
It does required more resources on production environment:
```
oc adm top pod tekton-results-watcher-6fb969985-bh7qm --containers
POD                                      NAME       CPU(cores)   MEMORY(bytes)
tekton-results-watcher-6fb969985-bh7qm   watcher    111m         1145Mi
```
Set cpu/memory requests quite low(100m/64Mi) to accommodate low traffic
environment and set limits high enough(250m/2Gi) for high traffic
environments.
PLNSRVCE-1476
=> Set cpu/memory requests/limits for tekton-results-watcher/watcher

operator/gitops/argocd/pipeline-service/tekton-results/watcher-config.yaml
This will enable the clean up of all PipelineRuns, including those having ownerReferences set to RHTAP resources.
Once the flag has been confirmed to work successfully, the default Pipelines pruner can be removed.
=> Disable 'check_owner' for Tekton Result watcher

.tekton/open-infra-deployment-pr.yaml
adding the kustomize output in the infra-deployment-update-script for missing staging/stone-stage-p01 path, so that the bot also update the deploy file for staging folder of pipeline-service
=> Add missing staging path file for deploy kustomize output

operator/gitops/argocd/pipeline-service/openshift-pipelines/chains-observability-service.yaml
This service is required by pipeline-service so this is why it is defined here rather than in OSP. Ignore the kube-linter issue as this is not a dangling service, the pod selector does match an existing deployment.
PLNSRVCE-1476
=> Ignore kube-linter dangling service issue for tekton-chains

operator/gitops/argocd/pipeline-service/tekton-results/watcher-config.yaml
Not sure how command line binary arguments are interpreted, but this seems to work.
=> Fix container argument syntax

operator/gitops/argocd/pipeline-service/tekton-results/api-s3-config.yaml
Tekton results API server memory averages to 100Mi, hence increasing the request to 128Mi.
Data from Prod for last 7days.
=> Increase memory request for tekton results API server

developer/images/dependencies-update/hack/bin/tasks/update_binaries.sh
The binaries are not available as soon as the release is created on GitHub, leading to CI failures. This change switches the source of the version to the release server.
=> Fix update of ROSA cli version

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
Tekton Results is now fully in charge of the deletion of pipelineruns
=> Disable OSP pruner

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
We'll maintain the default of 1 replica for the controller out of the gate in pipeline service
We'll overload for Konflux in infra-deployments once our related sanity check story around ensuring no negative performance of cluster capacity impacts have occurred when we separately enable multiple replicas in staging.
=> PLNSRVCE-1525: expose controller HA fields for possible gitops override

operator/gitops/argocd/pipeline-service/openshift-pipelines/osp-nightly-catalog-source.yaml
Here we only add the CatalogSource, but does not make use of it (does not reference it in the kustomization.yaml). An automation job will be including that reference until we switch to nightly builds.
=> Add CatalogSource including index with OSP nightly build

.github/workflows/update-osp-nightly.yaml
Currently this includes:
1. Check for nightly build and update the CatalogSource
2. Update the kustomization.yaml to add the CatalogSource
3. Update the Subscription to use the new CatalogSource and channel
Once we start using the nightly builds, we only need to update the CatalogSource to use the new index image (drop 2 and 3).
=> Create a PR to update OSP nightly deployment

.github/workflows/update-osp-nightly.yaml, .tekton/pipeline-service-upgrade-test-ocp-414.yaml, .tekton/pipeline/test-pipeline-service-upgrade.yaml
The nightly builds do not support downgrade. To revert to a previous version, a new version must be created revering the changes from the current one. In that case testing downgrade does not make sense.
=> Skip downgrade test for OSP nightly builds changes

operator/gitops/argocd/pipeline-service/openshift-pipelines/kustomization.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/namespace.yaml
ExternalSecrets are creates at sync-wave "-1" and they are required for services like Tekton Results and OSP. But for the secrets to be created, the namespace should exist in advance. Here we create the namespace before the secret. It does not affect the deployment of the OSP operator, it ignores the fact the namespace it tries to create already exist.
=> Create namespaces before external secrets

.tekton/pipeline-service-upgrade-test-ocp-414.yaml, .tekton/pipeline/test-pipeline-service-upgrade.yaml
Initially based on PR title which did not work as expected. Now based on source_branch, confirmed working on both new PR (create and update) and /test comment.
=> Fix skip downgrade test for OSP nightly updates

.github/workflows/update-osp-nightly.yaml, .tekton/open-infra-deployment-pr-osp-nightly.yaml
Each update for nightly builds will be pushed to a pipeline-service branch and that will trigger a job to open/update PR in infra-deployments.
=> Open/update PR in infra-deployments for each nightly

.github/workflows/update-osp-nightly.yaml
The intention always was to use a scheduler to execute the workflow daily. The manual trigger is kept for both easier testing and emergency updates.
=> Add cronjob trigger to OSP nightly workflow

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
From local testing:
```
tekton-operator-proxy-webhook-7f6d7f7d74-bf6xs       1/1     Running     0          2m31s
tekton-operator-proxy-webhook-7f6d7f7d74-mtcdr       1/1     Running     0          2m31s
tekton-pipelines-webhook-84c6fc988d-2kqzd            1/1     Running     0          2m32s
tekton-pipelines-webhook-84c6fc988d-srwdz            1/1     Running     0          2m32s
```
After seeing tests pass here with 2 replicas, I'll move down back to one replica, and bump the replicas via a gitops patch in infra-deployments
@openshift-pipelines/pipelines-service  FYI
=> PLNSRVCE-1526: expose core tekton webhook replicas setting in operator TektonConfig

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
This will include:
- chains controller
- PAC watcher and webhook; PAC controller currently does not have an upstream leader election config map
- remote resolvers controller
- any other core tekton stuff like eventing or triggers are not employed by Konflux
- reminder, the core tekton pipeline webhook has a horizontal autopod scaler that controlls the webhook's replica count
Validated with 2 replicas with local testing before setting back to 1
@openshift-pipelines/pipelines-service FYI / PTAL
=> PLNSRVCE-1526: expose in tektonconfig all relevant tekton deployments replicas count in openshift-pipelines

operator/gitops/argocd/pipeline-service/tekton-results/watcher-config.yaml
Manual testing with 2 replicas validated that leader election wired and functioning properly
Will override in infra-deployments
=> PLNSRVCE-1526: expose results watcher replica count in yaml

.tekton/open-infra-deployment-pr-osp-nightly.yaml, .tekton/open-infra-deployment-pr.yaml
The task we reference in the PipelineRun
quay.io/redhat-appstudio-tekton-catalog/task-slack-webhook-notification:0.1 is changed and the SCRIPT_IMAGE parameter removed. Instead a default image is used.
ref: https://github.com/redhat-appstudio/build-definitions/pull/792
The new image does not have `kustomize`, but it has `oc`, so we use `oc kustomize` instead.
=> Remove SCRIPT_IMAGE param from update infra-deployments task

operator/test/test.sh
to deal with the recent permfail in the results during test-upgrade (and only this permutation of the test)
@openshift-pipelines/pipelines-service FYI / PTAL
=> gather more diagnostic data on failures during results test

operator/gitops/argocd/pipeline-service/tekton-results/watcher-config.yaml
Discovered the need for this as a result of https://github.com/redhat-appstudio/infra-deployments/pull/3252#issuecomment-1937835777
Short term, the situation with the bitnami images and postgresql will sabatoge CI, but a manual apply -k of yaml shows the deployment is created fine and the watcher pod is started successfully
=> PLNSRVCE-1526: add affinity policies to results watcher

developer/openshift/apps/pipeline-service.sh, developer/openshift/gitops/local/kustomization.yaml, developer/openshift/gitops/local/openshift-pipelines/chains-secrets-config.yaml, developer/openshift/gitops/local/openshift-pipelines/kustomization.yaml, developer/openshift/gitops/local/openshift-pipelines/namespace.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/kustomization.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/public-key-secret.yaml, operator/test/test.sh
In order to facilitate backup/restore of a cluster, the signing secret is now stored externally and deployed on the cluster using an ExternalSecret.
The original behavior is maintained for local development.
=> Migrate Tekton Chains to an ExternalSecret

developer/images/devenv/Dockerfile
The git-2.43.0 version is no longer available, making the Dockerfile build (part of test-docker-images-build job) fail.
=> Fix git RPM version no longer available

.github/workflows/build-push-images.yaml, .github/workflows/individual-image-scanner-quay.yaml, .github/workflows/periodic-scanner-quay.yaml
The image is brittle because the image tag is floating. Since the image is just used for development, it should not be an issue to remove it from the CI.
=> Remove the developer/devenv image from the CI

.tekton/test-docker-images-build.yaml
seeing img build timeouts today in PR CI
=> bump test docker image build timeout to 1 hour

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-s3-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-config.yaml
add req/limit for operator proxy webhook
double req/limit for core webhook
equate results api/watcher requests/limits cpu/mem results watcher controller perf settings
As part of either the nightlies exposing 1.14+, or an explicit switch to 1.14 if something blocks nightly propagation, 
I'm exposing horizontal pod autoscalers and related deployment cpu/mem req/limit for the webhooks.
there was some results req/limit settings that needed to be made equal to ensure obtaining of those value from k8s, as we saw some instances where more mem was denied while below the mem limit 
=> expose autoscaler for both webhooks

operator/gitops/argocd/pipeline-service/openshift-pipelines/chains-secrets-config.yaml, operator/test/test.sh
Now that the secret is managed by an ExternalSecret, the secret should not be immutable so the secret can be synced.
=> Remove immutability to chains signing-secrets

.github/workflows/update-osp-nightly.yaml
The peter-evans/create-pull-request GH action has newer version fixing the "Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20" error.
=> Update the update-osp-nightly GH action

operator/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml
Use newer Tekton Results version including the "Support all data types in summary annotations" (fix for the json unmarshal bug). Drop the "employ some channel best practices to avoid hanging goroutines and memory leaks from unclosed buffered channels" commit.
The commit is from the downstream-0.9.1-03-no-21d96ba branch on the Results fork.
=> Use newer Tekton Results version

operator/test/test.sh
to better assist in debugging the chains error introduced with https://github.com/openshift-pipelines/pipeline-service/pull/985
@yashvardhannanavati @arewm @lcarva FYI
=> fix wait_for_pipelines debug

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
A followup to https://github.com/openshift-pipelines/pipeline-service/pull/989(closed accidently, and not able to reopen it)
=> add grafana views for tekton chains controller workque and latency

ci/images/ci-runner/Dockerfile, ci/images/e2e-test-runner/Dockerfile, developer/images/dependencies-update/Dockerfile
Update to newer ubi-minimal base image version and the respective rpm versions.
=> Fix missing git rpm version

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
So the grafana suggested use of rate proved flaky in prod for what we need for the tekton results api success rate for basic debug, which includes historical
If we were ever to use this for alerts, we'll add a panel that does the `increase(...)` to adjust for resets, etc.
for more on rate vs. increase some internet searching will get you deep dive break downs like https://stackoverflow.com/questions/54494394/do-i-understand-prometheuss-rate-vs-increase-functions-correctly
We now have 
@jkhelil @enarha ptal
@savitaashture fyi
=> fix flaky tekton results api success rate panel

operator/gitops/argocd/pipeline-service/metrics-exporter/deployment.yaml
per https://go.dev/doc/diagnostics it is safe to run with pprof in production, where the only perf impact of any note is if you explicitly enable cpu profiling or tracing.
this allows us to do spot profiling, or minimally, get thread dumps with ease.
=> enable pprof on metrics exporter

.tekton/open-infra-deployment-pr-osp-nightly.yaml, .tekton/open-infra-deployment-pr.yaml
undo only half of https://github.com/openshift-pipelines/pipeline-service/pull/1007 as the older watcher and newest api server work OK together
let's keep the api server tuning options
@enarha PTAL
=> pin watcher to mem leak version, revert latest fix attempt

.tekton/open-infra-deployment-pr-osp-nightly.yaml, .tekton/open-infra-deployment-pr.yaml
@enarha and I were able to test this locally
=> switch back off yq for sed for pinning watcher image, but get it working

operator/gitops/argocd/pipeline-service/metrics-exporter/deployment.yaml, operator/gitops/argocd/pipeline-service/metrics-exporter/kustomization.yaml
this should properly consume the update from https://github.com/openshift-pipelines/pipeline-service-exporter/pull/70
=> SRVKP-5825: move to exporter image in quay.io/konflux-ci

ci/docs/continuous_integation.md
=> update ci doc for tekton-ci to konflux-ci move

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
This is already enabled and used in Konflux (see
https://github.com/redhat-appstudio/infra-deployments/pull/3693 and https://github.com/redhat-appstudio/infra-deployments/pull/3818). Without having the configuration in pipeline-service, updates were overriding the values. This will not generate diff in Konflux.
=> Enable Tekton step-actions

operator/gitops/argocd/pipeline-service/openshift-pipelines/chains-secrets-config.yaml
The change was wrongly introduced in the infra-deployments deploy.yaml files, making the updates from pipeline-service to override the change.
ref: https://github.com/redhat-appstudio/infra-deployments/pull/3848
=> Update appstudio-utils image ref

operator/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml
fyi no direct image specs in Deployments in https://github.com/openshift-pipelines/pipeline-service/tree/main/operator/gitops/argocd/pipeline-service/tekton-results
that said let's wait until https://github.com/openshift-pipelines/tektoncd-results/pull/70 merges to confirm
=> SRVKP-5832: move to downstream images to quay.io/konflux-ci

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
see https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1721742678863629
@enarha @gbenhaim
=> add OSP pruner back as backup to results

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json, operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
@divyansh42 FYI
based on my monitoring of prod-rh01 via OCP metrics panel k8s throttling still correlates with the taskrun_pod_create metric so I'm filtering those taskruns from the total
the throttle_by_quota metrics are part of your SRVKP-4422 validation effort, hence the cross referernce
=> SRVKP-4532: factor k8s throttling into task panel

operator/gitops/argocd/pipeline-service/metrics-exporter/clusterrole.yaml
For new resolver deadlock metric given recent hangs/crashloops
Metric coming with https://github.com/openshift-pipelines/pipeline-service-exporter/pull/71
@enarha @savitaashture @khrm @divyansh42 FYI
=> SRVKP-4532: add resolver crd to exporter permissions

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
after fixing the pruner config typo, using disabled instead of disable, kept getting this inexplicable error in the operator validating webhook, even though only 'keep-since' was used and not 'keep'
`validation failed: expected exactly one, got both: spec.pruner.keep, spec.pruner.keep-since,Reason:BadRequest,Details:nil,Code:400,`
only disabling pruning seems to bypass this error in my `fix-pruner-cfg` branch here.
Currently main branch fails dev_setup.sh with the typo.
so @enarha @divyansh42 yeah there is some weird impl detail with gitops in conjunction with tekton operator
In fact after first changing line 197 in the file to say `disabled` vs. `disable` and seeing the validation error above, and then just disabling the pruner, when I ran
`oc get tektonconfig config -o yaml -w` I would …
=> disable pruning temporarily, work around weird operator validation error
