openshift-pipelines/pipeline-service

run.sh
Note: Pipeline repo changes is made on the pipeline repo.
=> Modified run.sh to install just the required CRDs from pipeline repo

run.sh
With the merge of https://github.com/tektoncd/pipeline/pull/4459, Task, ClusterTask, and Pipeline CRDs are optional. 
The controller will start fine even if the cluster doesn’t know about them.
=> Use tektoncd/pipeline main branch

README.md, run.sh
* Update documentation with required configuration
* Avoid using host.docker.internal when podman is used
=> Run on Fedora with podman

run.sh, sink.patch, workspace.yaml
2 changes:
* A workspace is required now. Otherwise, objects are not synced.
* Namespace names changed: it is the hash of the logical cluster name + namespace.
=> Bump kcp to latest version

ckcp/.gitignore, ckcp/run.sh
Added a variable to refer to kcp kubeconfig - **KUBECONFIG_KCP**
Local Run:
```
./run.sh pipelines
./test.sh pipelines
```
```
[bnr@bnr ckcp]$ k -n ckcp get pods
NAME                    READY   STATUS    RESTARTS   AGE
ckcp-76ff95585f-chh79   1/1     Running   0          3m14s
[bnr@bnr ckcp]$ 
[bnr@bnr ckcp]$ k -n pipelines get pods
NAME                         READY   STATUS    RESTARTS   AGE
pipelines-57785c787b-t775g   1/1     Running   0          100s
[bnr@bnr ckcp]$ 
[bnr@bnr ckcp]$ 
[bnr@bnr ckcp]$ 
[bnr@bnr ckcp]$ k get ns | grep -i kcp
ckcp                                                          Active   3m36s
kcpe2cca7df639571aaea31e2a733771938dc381f7762ff7a077100ffad   Active   55s
[bnr@bnr ckcp]$ 
[bnr@bnr ckcp]$ 
[bnr@bnr ckcp]$ k -n …
```
=> Modified ckcp/run.sh to use kustomize instead of git clone and applying patch files for pipelines

ckcp/gitops.sh
I've used `foxundermoon.shell-format` in VSCode to autoformat the script to have consistent formatting throughout the file.
=> ckcp/gitops.sh clean-up/formatting

DEVELOPMENT.md, local/argocd/ingress.yaml, local/argocd/setup.sh, local/kind/ingress-router.yaml, local/kind/setup.sh
This documents and automates the installation of Argo CD in the development environment.
This is a first step towards getting Pipelines Service entirely deployed and managed through GitOps.
=> Installation of Argo CD as part of the development setup

ckcp/gitops.sh
According remaining change for https://github.com/openshift-pipelines/pipelines-service/commit/6d7ccf1603b9bc3189703449d49415c719690b50
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>
=> Fix installation pipeline and trigger argocd applications for gitops.sh script.

local/argocd/setup.sh
=> fix: sleep command parameter => mac os compatible

kcp/README.MD
=> Remove references to the login script from the kcp README

.github/workflows/argocd-registrar-image.yaml, .github/workflows/kcp-registrar-image.yaml
=> Added GitHub workflows to publish images to ghcr

.github/workflows/cluster-setup-image.yaml, gitops/pac/.tekton/pln-svc-registration.yaml, images/cluster-setup/Dockerfile
- This PR follows PR #85.
- While 85 has the script, files, and folders to make the changes to adhere to Phase 1 architecture, this PR has the Dockerfile and the PipelineRun yaml which will automate the workflow using PAC. 
Local Tests:
=> PLNSRVCE-188 : Conform to the mid term architecture - Part 2 

local/kind/setup.sh
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
Fixes #101
=> Setting PODMAN_CMD explicitly to podman

CONTRIBUTING.md, DEVELOPMENT.md, README.md, ckcp/README.md, docs/gateway.md, docs/kcp-registration.md, exploration/argocd-external/docs/argocd.md, gitops/README.md, gitops/pac/README.md, gitops/sre/credentials/kubeconfig/README.md, kcp/README.MD
- Used same code-fencing style(backticks) throughout the project
- Fixed spelling and grammetical errors
- Applied formatting and lint
- Removed redundant lines
Signed-off-by: Avinal Kumar <avinkuma@redhat.com>
=> Improve markdown files for consistency and grammar

images/kcp-registrar/register.sh
Fixes issues introduced by PR #86 that break the script logic for kcp registration
=> Fixes issues introduced by #PR86 that break the script logic for kcp registration

DEVELOPMENT.md
Added troubleshooting for the following:
- Error: can only create exec sessions on running containers: container state improper
- Failed to create kind cluster - "Reached target ._Multi-User System._|detected cgroup v1"
- Looping with "error: availableReplicas is not found"
- "Kind could not be found" when running with sudo
Signed-off-by: Avinal Kumar <avinkuma@redhat.com>
=> Add more troubleshooting scenarios

images/cluster-setup/install.sh
With the current script, was running into the below issue. Fixed it by replacing the postchecks function with a simpler check of deployments instead of pods. 
```
Checking deployment
- api-ci-ln-gpg06s2-72292-origin-ci-int-gce-dev-rhcloud-com:
- tekton-pipelines-controller: error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
template was:
{.items[0].metadata.name}
object given to jsonpath engine was:
map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```
Tested it by running the script on a cluster-bot cluster.
```
[bnr@bnr pipelines-service]$ …
```
=> Fix install.sh script

ckcp/openshift_dev_setup.sh
**Changes**
Improved the validation that resources are synced to KCP. It just verify the resource that stored in  $TEKTON_CRDS.
=> Loop issue

ckcp/README.md
=> Document kcp plugin version in ckcp/README

images/cluster-setup/install.sh
Some arrays were not initialized properly, generating errors when more than
one element was present.
Some cosmetic changes to the output to make it a bit more compact.
=> Fix array initialization

images/access-setup/content/bin/setup_compute.sh
=> fix: Incorrect variable initialization

ckcp/README.md, ckcp/openshift_dev_setup.sh, gitops/pac/setup.sh, images/access-setup/content/bin/setup_compute.sh
Update openshift_dev_setup to leverage the scripts used to deploy the
service on production clusters.
=> Use access_setup to setup KCP and the compute

ckcp/openshift_dev_setup.sh, images/kcp-registrar/register.sh
=> Deprecate some CRDS from the kcp_syncer

local/kind/setup.sh
=> Fixes issue with rootless local kind clusters

ckcp/openshift_dev_setup.sh
**Changes:**
Added one check that attempts to perform a dry-run create of a cert-manager Certificate resource in order to verify that CRDs are installed and all the required webhooks are reachable by the K8S API server.
=> perform a dry-run create of Certificate for cert-manager check 

ckcp/openshift_dev_setup.sh
=> Fixed "yq can't read /tmp dir"

.github/workflows/kcp-registrar-image.yaml, ckcp/README.md, ckcp/openshift/overlays/dev/kustomization.yaml, ckcp/openshift_dev_setup.sh, images/gateway-deployment/install.sh, images/kcp-registrar/register.sh, local/.utils, local/kcp/pipelines-service-org.yaml, local/kcp/start.sh, local/kind/us-east1.yaml, local/kind/us-west1.yaml
=> Upgrade kcp to release-0.6

.github/workflows/shellcheck-image.yaml
**Changes:**
Corrected the path of Shellcheck Docker file
=> fix the path of shellcheck Docker file

DEVELOPMENT.md, images/access-setup/content/bin/setup_compute.sh
=> Fix yq issue with accessing root filesystem when installed via snap

docs/kcp-registration.md
=> Align documentation with the new repo structure: removal of gitops directory

.github/workflows/access-setup-image.yaml, images/access-setup/Dockerfile, images/access-setup/content/bin/setup_compute.sh
* Check that ArgoCD has been installed on the compute cluster
* Do not change workspace if we're already in the right one
=> bugfix: access_setup

gitops/README.md
=> Fix parameter name in gitops readme

images/access-setup/content/bin/setup_compute.sh, images/access-setup/content/bin/setup_kcp.sh
=> Amend description: mandatory arguments were described as optional

OWNERS
**Changes:**
Added `OWNERS` file to the repo so that openshift-ci can manage merge process for us, i.e. merging automatically after review&approval
=> add owners file for openshift-ci to manage merge process

exploration/argocd-external/images/argocd-registrar/register.sh, images/access-setup/content/bin/setup_compute.sh, images/access-setup/content/bin/setup_kcp.sh, images/cluster-setup/install.sh, images/gateway-deployment/install.sh, images/kcp-registrar/register.sh, local/kcp/start.sh, local/kind/setup.sh
=> Clean-up all shellcheck issues

images/access-setup/content/bin/common.sh
**Issue**
The secrets for the pac-manager SA tokens are created asynchronously. For now we need to wait for their creation before trying to extract the token form them.
**Changes**
Wait until pac-manager SA token is created before trying to extract the token form them.
=> fixed issue of  extracting SA token

.github/workflows/local-dev-ci.yaml
**Changes**
Added a CI for testing local dev environment
=> add ci for testing local dev environment

README.md
=> Add new recordings to the readme page

test/config/hadolint.yaml
**Changes:**
Added Hadolint configuration file for configuring rules. The CI job is implemented with Openshift CI, this is the [PR](https://github.com/openshift/release/pull/31602)
=> added  Hadolint configuration file

ckcp/README.md, ckcp/config.yaml, ckcp/hack/util/update-git-reference.sh, ckcp/openshift_dev_setup.sh, gitops/pac/setup.sh, images/access-setup/content/bin/setup_compute.sh
* A new `config.yaml` file containing various defaults, and an alteration in this file will be reflected in the `./ckcp/openshift_dev_script.sh`.
* List of CRs and applications to be deployed with ckcp are now customizable.
Fixes #181
=> Improving Developer Experience with ckcp

ckcp/openshift_dev_setup.sh
`ckcp`'s deployments depend on `cert-manager` operator. `Cert-manager` is only deployed with the deployment of `Pipeline-Service` on the compute. And thus `ckcp` is dependent upon another service to be deployed on the host cluster.
=> fix cert-manager sync with ckcp

test/config/checkov.yaml
**Changes:**
Added config file for SAST tools Checkov. The Checkov [CI PR](https://github.com/openshift/release/pull/31716) relies on this PR.
You could reference [CLI Command Reference](https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html) for the the properties in config file.
**Verify:**
You can execute the command with its Docker image to see the result.
```
$ docker run -it --rm --volume <the path of pipelines-service directory>:/tf --workdir /tf bridgecrew/checkov  --directory /tf --config-file /tf/test/config/checkov.yaml
```
=> added config file for SAST tools Checkov

.github/workflows/individual-image-scanner-quay.yaml, .github/workflows/periodic-scanner-quay.yaml, test/images/vulnerability-scan/Dockerfile, test/images/vulnerability-scan/scan-image.sh, test/images/vulnerability-scan/scan.sh
- Added the image (Dockerfile + script) for future consumption in Pipeline Runs.
- For now, created a Github Action to use the same script to fetch the results to check for vulnerabilities in our images on quay.
- Have also setup Authorization token via Github secrets.
=> PLNSRVCE-522 : Containers - Clair - Vulnerability Scanner

test/images/vulnerability-scan/Dockerfile
**Changes:**
This issue was reported by hadolint. By default, curl command already is installed in the , it's no needed to install it.
=> fixed minor issues reported by hadolint

local/kcp/start.sh
This is for the local dev setup.
=> Make the location of kcp runtime files configurable

ckcp/openshift/base/deployment.yaml
as requested by checkov
using [the configuration provided by the kcp project]( https://github.com/kcp-dev/helm-charts/blob/main/charts/kcp/templates/kcp.yaml#L243-L268)
=> Add probes to ckcp

local/kcp/start.sh
=> Document how params need to be passed

ckcp/openshift_dev_setup.sh
**Changes:**
Recently we often saw ckcp failed at waiting ckcp up.  So added a debug switch to print more information for debugging the failure when it fails.
=> add debug switch for debugging ckcp error

DEVELOPMENT.md, ckcp/README.md, ckcp/openshift_dev_setup.sh, ckcp/test.sh, gitops/README.md, gitops/argocd/tektoncd/tekton-config.yaml, images/access-setup/content/bin/setup_compute.sh
- Some information in ckcp README was obsolete. Updated it.
- Replaced ArgoCD to Argo CD.
=> Improve README in ckcp

test/images/vulnerability-scan/common/utils.sh, test/images/vulnerability-scan/scan-image.sh, test/images/vulnerability-scan/scan.sh
Also, modified scan.sh and scan-image.sh scripts to call methods from util script where the common functions are stored.
=> Created a util script for vulnerability scan image

ckcp/README.md
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
=> Fix broken links in ckcp docs

images/kcp-registrar/register.sh
Current behavior generates the following issues:
- An upgrade of the KCP version will not deploy existing syncers.
- KCP syncers can have different version for each cluster, which breaks
consistency.
- If the creation of the syncer on the compute cluster fails for any reason,
the syncer will not be deployed on the next run as it is already declared
in the KCP workspace.
Proposed behavior generates the following issues:
- An upgrade of the KCP version will deploy on all clusters, which may trigger
an interruption of service if there is an issue with the syncer.
- The team operating the KCP workspace into which the clusters are registered
cannot customize the configuration of the syncer, as it would get overwritten
at every run.
=> Always register clusters to KCP

images/kcp-registrar/register.sh
This ensures a more secure and correct connection from the syncer to the workspace.
I ran into certificate issues when deploying pipeline-service into an existing kcp instance in OpenShift.
=> Record server CA during registration

ckcp/openshift_dev_setup.sh
Includes a small refactor to create and use the PROJECT_DIR var.
=> Propagate debug flag in ckcp/openshift_dev_setup.sh

DEPENDENCIES.md, images/kcp-registrar/Dockerfile
=> Fix missing openssl dependency in kcp-registrar Dockerfile

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/build-push-images.yaml, CONTRIBUTING.md, config/dependencies.yaml, local/utils.sh, test/images/devenv/Dockerfile, test/images/devenv/README.md, test/images/devenv/install.sh, test/images/devenv/run.sh
A container with all the required dependencies is defined, which the user can use as a development platform.
VS Code support for the 'Remote Development' extension is introduced to leverage that container when using the IDE.
=> Provide a development container to minimize devenv setup

images/cluster-setup/Dockerfile
=> Fix missing jq dependency in cluster-setup Dockerfile

images/kcp-upgrade/upgrade.sh
- kcp version is shown as 0.8.2 instead of the usual v0.8.2 in a couple of file in the repo. Made changes in the upgrade script to take care of this as well.
=> Updating kcp upgrade script

.github/workflows/build-push-images.yaml
=> Fix devenv image generation

ckcp/README.md, ckcp/hack/util/reset_ckcp.sh
=> Script to reset ckcp

OWNERS
=> add RAMESSESII2 to the OWNERS.md

ckcp/manifests/tekton-results-db/openshift/configmap.yaml, ckcp/manifests/tekton-results-db/openshift/kustomization.yaml, ckcp/manifests/tekton-results-db/openshift/namespace.yaml, ckcp/manifests/tekton-results-db/openshift/service.yaml, ckcp/manifests/tekton-results-db/openshift/statefulset.yaml, ckcp/openshift_dev_setup.sh, ckcp/test.sh, config/config.yaml, gitops/argocd/argo-apps/kustomization.yaml, gitops/argocd/argo-apps/tekton-results.yaml, gitops/argocd/tekton-results/README.md, gitops/argocd/tekton-results/allow-argocd-to-manage.yaml, gitops/argocd/tekton-results/cert.yaml, gitops/argocd/tekton-results/configmap.yaml, gitops/argocd/tekton-results/deployment.yaml, gitops/argocd/tekton-results/kustomization.yaml, gitops/argocd/tekton-results/permissions.yaml, gitops/argocd/tekton-results/route.yaml, gitops/argocd/tekton-results/service-account.yaml, images/access-setup/README.md, images/access-setup/content/bin/setup_compute.sh, images/cluster-setup/bin/install.sh
Implement Tekton Results and Postgresql DB for openshift development
Signed-off-by: Cathal O'Connor [cathal@redhat.com](mailto:cathal@redhat.com)
=> PLNSRVCE-420 : Implement Tekton results for openshift development

gitops/argocd/tekton-results/deployment.yaml
Update tekton results images to pipeline-service built images
=> Update tekton results images to pipeline-service built images

test/images/quay-upload/image-upload.sh
latest_tag_on_quay was not set properly.
Logging has been improved.
=> fix: Invalid var assignement in impage-upload.sh

test/images/devenv/Dockerfile
=> Fix image SHA for the devenv image

ckcp/manifests/tekton-results-db/openshift/configmap.yaml, ckcp/manifests/tekton-results-db/openshift/namespace.yaml, ckcp/manifests/tekton-results-db/openshift/service.yaml, ckcp/manifests/tekton-results-db/openshift/statefulset.yaml, ckcp/test.sh, gitops/argocd/tekton-results/allow-argocd-to-manage.yaml, gitops/argocd/tekton-results/cert.yaml, gitops/argocd/tekton-results/configmap.yaml, gitops/argocd/tekton-results/deployment.yaml, gitops/argocd/tekton-results/permissions.yaml, gitops/argocd/tekton-results/route.yaml, gitops/argocd/tekton-results/service-account.yaml, images/access-setup/content/bin/setup_compute.sh
Update tekton-results path so that it is deployed in its own namespace
Closes #281
=> update tekton-results path

test/images/quay-upload/image-upload.sh
The current script would not upload the right images when there is multiple branches in the repository.
The refactored script also leverage environment variables that are expected to be set to decrease reliance on external services.
=> Refactor image upload

.github/workflows/build-push-images.yaml, test/images/quay-upload/image-upload.sh
=> image-upload: Add usage and fix registry path

ckcp/openshift_dev_setup.sh, config/config.yaml, images/kcp-registrar/bin/register.sh
=> Remove runs.tekton.dev from kcp-syncer

ckcp/test.sh, config/dependencies.yaml, test/images/shellcheck/Dockerfile
Fix new issues as part of the upgrade.
=> Upgrade shellcheck from v0.7.1 to v0.8.0

.github/workflows/build-push-images.yaml, test/images/yamllint/Dockerfile
This PR is to build yamllint image and push it to quay.io
=> build yamllint image

images/kcp-upgrade/upgrade.sh
This PR fixes the failed action due to a path change - https://github.com/openshift-pipelines/pipeline-service/actions/runs/3257784935/jobs/5349315277#step:3:12
=> Fix the path as a previous PR changed the path of register.sh script

images/access-setup/Dockerfile, images/kcp-upgrade/upgrade.sh
=> Fix kcp-upgrade to handle access-setup

test/images/devenv/install.sh
The script can be run as a standard user to install all the dependencies in their environment.
=> Improve devenv/install.sh script

images/update-pipeline-service/bin/gitlab_open_mr.sh, test/images/quay-upload/image-upload.sh
Fixed all errors of type 'SC2269 (info): This variable is assigned to itself,so the assignment does nothing.'
=> Fix shellcheck errors

consumer/README.md, consumer/bind_to.sh, consumer/manifests/apibinding/apibinding.yaml, consumer/manifests/workloads/hello-world.yaml, consumer/run_test_workload.sh
This commit is part of a larger set of commits with the goal of restructuring the repository.
=> refactor: Create 'consumer' folder

.tekton/pipeline-service-static-code-analysis.yaml
This PR is to set the PipelineRun's failure timeout.
=> Configuring a failure timeout

.github/workflows/build-push-images.yaml
=> Fix YAML formatting for .github/workflows/build-push-images.yaml

.tekton/pipeline-service-static-code-analysis.yaml, consumer/README.md, consumer/bind_to.sh, consumer/hack/bind.sh, consumer/hack/run_test_workload.sh, consumer/run_test_workload.sh
=> consumer: Add scripts to access service

.tekton/pipeline-service-ckcp-testing.yaml
This PR is to implement ckcp CI with Pipelinerun CR, which can be triggered on pipeline-serivce when PR or Push occurs. The exiting CI will be removed from openshift CI https://github.com/openshift/release/pull/33909
=> implemented ckcp CI with pipeline-service

developer/ckcp/openshift_dev_setup.sh, operator/images/kcp-registrar/bin/register.sh
This change should help deploying ckcp in a standalone manner.
=> ckcp can now be run without any app

operator/gitops/argocd/tekton-results/kustomization.yaml, operator/gitops/argocd/tekton-results/service.yaml
Move API service from CKCP install to operator install so that it's installed in all environments.
=> Move api service yaml

.tekton/pipeline-service-ckcp-testing.yaml, operator/test/test.sh
This PR is to add test.sh in CKCP CI and verify the pipelineruns case. Becuase GRPC doens't work for now when verifying pipeline result, it was moved out from test_pipelines funcation
=> added test in ckcp ci

developer/hack/build_image.sh, developer/hack/run_image.sh
This should help with developing/maintaining/testing the various scripts bundled in images.
=> Add script to build and run images

.github/workflows/dependencies-update.yaml
=> Fix .github/workflows/dependencies-update.yaml

.tekton/pipeline-service-test.yaml
1. Renamed CI name `pipeline-service-ckcp-test` to `pipeline-service-test`
2. Using `developer/openshift/dev_setup.sh` to set up pipeline-service in an OCP cluster
3. Executing `operator/test/test.sh` to verify pipeline-service
4. Refactor the CI tasks and steps
=> change ci to aligh with the refacored pipeline-service repo

.tekton/pipeline-service-static-code-analysis.yaml
=> Use the static-checks image in the CI tekton task

.github/workflows/build-push-images.yaml, .github/workflows/dependencies-update.yaml, .github/workflows/individual-image-scanner-quay.yaml, .github/workflows/periodic-scanner-quay.yaml, developer/images/dependencies-update/Dockerfile, developer/images/dependencies-update/content/bin/tasks/update_dockerfiles_base_images_sha.sh, developer/images/dependencies-update/content/bin/update.sh
This image will subsequently be used in a tekton task.
=> Bundle dependencies-update into an image

operator/gitops/argocd/pipeline-service/tekton-results/deployment.yaml, operator/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml
Replace tekton-results image refs with a placeholder so that we can update the desired tag through scripting.
=> Allow kustomization of tekton-results

developer/openshift/dev_setup.sh, developer/openshift/manifests/tekton-results-db/openshift/statefulset.yaml, operator/gitops/argocd/pipeline-service/tekton-results/deployment.yaml
- Fix the config mount path for tekton-results-api. This seems to have
changed after latest image update.
- instruction to install postgres-db in dev environment was accidentally
removed in 64ceee84af. This has been fixed
=> Fix tekton-results

developer/openshift/reset.sh
update reset script for pln-svc
- remove kcp-infra specific code
- add code to remove tekton-chains and tekton-results controller
- 
One can do a `./developer/openshift/reset.sh -h ` to see all the options available with reset script to scrap the deployed pipeline-service deployments.
=> update reset script for pln-svc

.github/workflows/dependencies-update.yaml
=> fix Upgrade dependencies github action

developer/images/devenv/Dockerfile
=> Update base image for devenv to fix a cve

.tekton/pipeline-service-test.yaml
**Description:** 
This PR added a new task which will run in parallel with deploy-cluster to clean any hypershift cluster that's older than 1hr
=> added task to run in parallel with deploy-cluster to clean useless clusters 

.github/workflows/build-push-images.yaml, .github/workflows/individual-image-scanner-quay.yaml, .github/workflows/periodic-scanner-quay.yaml, .tekton/pipeline-service-static-code-analysis.yaml, .tekton/pipeline-service-test.yaml, ci/images/ci-runner/hack/manifests/sidecar/kustomization.yaml, ci/images/ci-runner/hack/manifests/sidecar/pod.yaml, ci/images/ci-runner/hack/manifests/sidecar/pvc.yaml, ci/images/ci-runner/hack/sidecar/bin/plnsvc_setup.sh, ci/images/ci-runner/hack/sidecar/bin/plnsvc_test.sh, operator/gitops/argocd/pipeline-service/tekton-chains/chains-config.yaml
=> Fix files to pass static checks

developer/images/dependencies-update/content/bin/tasks/update_binaries.sh
=> Add script to fetch the latest binary versions

developer/images/dependencies-update/content/bin/tasks/update_binaries.sh
Make sure that versions only roll forward.
=> Fix update_binaries

ci/images/ci-runner/Dockerfile, ci/images/quay-upload/Dockerfile, ci/images/static-checks/Dockerfile, ci/images/vulnerability-scan/Dockerfile, developer/images/dependencies-update/Dockerfile, developer/images/devenv/Dockerfile, operator/images/access-setup/Dockerfile, operator/images/cluster-setup/Dockerfile, operator/images/update-pipeline-service/Dockerfile
Updated ubi9 minimal image's SHA in all the Dockerfiles.
=> Fix CVEs reported on images in our repo

shared/config/dependencies.sh
=> Fix bitwarden version

ci/docs/continuous_integation.md, ci/docs/rosa_cluster_provision.md, ci/hack/hypershift_setup.sh, ci/hack/rosa_cluster_provision.sh, ci/manifests/hypershift/hypershift_operator_install.yaml, ci/manifests/hypershift/manage_cluster.yaml, ci/manifests/hypershift/multi_cluster_engine.yaml
This changes aims to add the documentation for pipeline service CI setup
Signed-off-by: Priti Kumari [pkumari@redhat.com](mailto:pkumari@redhat.com)
=> PLNSRVCE-1003: Pipeline service CI setup documentation

developer/images/devenv/Dockerfile
=> Fix devenv image

.tekton/update-dependencies.yaml, developer/images/dependencies-update/hack/bin/is-pr-skipped.sh, developer/images/dependencies-update/hack/bin/setup-local-repository.sh
=> Fix pipeline-service-update-dependencies

operator/gitops/argocd/pipeline-service/tekton-chains/chains-secrets-config.yaml, operator/gitops/argocd/pipeline-service/tekton-chains/kustomization.yaml, operator/gitops/argocd/pipeline-service/tekton-chains/public-key.yaml, operator/test/manifests/test/tekton-chains/public-key.yaml, operator/test/test.sh
A secret is used as EnterpriseContract currently does not support ConfigMap.
=> Share tekton-chains public key with all users

operator/test/test.sh
This PR is to fix the issue of Trigger test, which missed a [rbac.yaml](https://raw.githubusercontent.com/tektoncd/triggers/v0.18.0/examples/rbac.yaml).
=> fixed issue of trigger test

operator/gitops/argocd/pipeline-service/tekton-chains/chains-secrets-config.yaml
=> Fix tekton-chains-signing-secret deployment

ci/docs/continuous_integation.md
Due to InfoSec best practices removing few info from public repo
Signed-off-by: Priti Kumari [pkumari@redhat.com](mailto:pkumari@redhat.com)
=> Remove few info from public repo

developer/images/dependencies-update/hack/bin/task.sh, developer/images/dependencies-update/hack/bin/tasks/update_dockerfiles_base_images_sha.sh
Files were not added before commiting the changes
=> Fix automatic update

operator/test/test.sh, shared/hack/install.sh
Quite a lot of whitespace changes because of autoformatting.
You have the option to ignore those during the review by clicking 'Files changed', then the gear icon and enabling `Hide whitespace`.
=> Fix static checks errors

developer/openshift/README.md, developer/openshift/dev_setup.sh
Fix an issue with how changes to the upstream are detected
=> Fix dev_setup.sh

developer/openshift/gitops/argocd/pipeline-service/tekton-results/s3-configuration-patch.yaml
Workaround for https://github.com/minio/operator/issues/1346
=> Create minio bucket using init container

ci/images/ci-runner/hack/bin/utils.sh
It fixed the issues that prints out secret information 
Signed-off-by: Xin Jiang @xinredhat
=> fix the issue to avoid printing out secret information

.tekton/push.yaml
fix to https://github.com/openshift-pipelines/pipeline-service/pull/502
=> PLNSRVCE-1105: fix pac push job to update pipeline-service sha refs in infra-deployments

.tekton/infra-deployment-push.yaml.disable
see https://github.com/openshift-pipelines/pipeline-service/pull/513#pullrequestreview-1311263800 and https://github.com/openshift-pipelines/pipeline-service/pull/513#issuecomment-1441910863
=> PLNSRVCE-1105: a STONEBLD-777 inspired update to the newer appstudio bundle for the PaC push job

developer/openshift/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml, developer/openshift/gitops/argocd/pipeline-service/tekton-results/log-clusterrolebinding.yaml, developer/openshift/gitops/argocd/pipeline-service/tekton-results/s3-configuration-patch.yaml
To make working s3 we also need https://github.com/openshift-pipelines/tektoncd-results/pull/33
=> Fix s3 streaming

operator/gitops/argocd/pipeline-service/openshift-pipelines/openshift-operator.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
Locally tested ✔️  
and there doesn't seem to be any breaking changes. 
=> PLNSRVCE-1030: upgrade Openshift-Pipelines to 1.9

ci/docs/continuous_integation.md, ci/hack/hypershift_setup.sh, ci/hack/rosa_cluster_provision.sh
For now CI job switched to use Hyperhift Cli for creating and deleting Hypershift hosted cluster. This PR updated the scripts for the process of Hypershift Setup.
Signed-off-by: Xin Jiang @xinredhat
=> update pipeline-service ci setup

.tekton/pipeline-service-downgrade-test.yaml, operator/images/cluster-setup/content/bin/install.sh
A new CI test the downgrade path
=> PLNSRVCE-1179: CI test the downgrade path

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
See https://docs.openshift.com/container-platform/4.11/cicd/pipelines/op-release-notes.html#resolver-new-features-1-9_op-release-notes
=> Enable resolvers in openshift-pipelines

ci/images/ci-runner/hack/bin/deploy-cluster.sh
It print credentials in the output, which is  useful for debugging
=> print out hypershfit cluster credential

developer/openshift/gitops/argocd/pipeline-service/tekton-results/minio-create-bucket.yaml
Change the repo of image mc to pont ot quay.io. this can avoid the error `You have reached your pull rate limit`
=> change the repo of image mc to quay.io

.github/workflows/build-push-images.yaml, .github/workflows/individual-image-scanner-quay.yaml, .github/workflows/periodic-scanner-quay.yaml
Added e2e-test-runner image required to run the build and scan CI
=> build and scan e2e-test-runner image

.github/workflows/individual-image-scanner-quay.yaml
The dependencies-updaet image job was not configured properly
=> Fix the configuration of the image scanner

developer/openshift/gitops/argocd/pipeline-service/kustomization.yaml, developer/openshift/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml, developer/openshift/gitops/argocd/pipeline-service/tekton-results/minio-create-bucket.yaml, developer/openshift/gitops/argocd/pipeline-service/tekton-results/minio-tls.yaml
https://github.com/openshift-pipelines/pipeline-service/pull/545
=> Revert tls patch to fix connection tekton-result api and Minio S3

.tekton/hack/setup_pipeline-service-ci.sh, .tekton/manifests/kustomization.yaml
* Fix GitHub public key
* Fix setup script
=> Fix pipeline-service-ci setup

ci/images/ci-runner/hack/bin/destroy-clusters.sh
This is to fix a minor issue that the hostedcluster doesn't exist.
=> fixed issue of destroying exisint clusters

.tekton/pipeline-service-static-code-analysis.yaml, ci/images/static-checks/content/bin/hadolint.sh, ci/images/static-checks/content/bin/yamllint.sh
stemmed from https://github.com/openshift-pipelines/pipeline-service/pull/577#discussion_r1165929770 and https://github.com/openshift-pipelines/pipeline-service/pull/577#discussion_r1165962007
=> fix: update shellcheck/yamllint/hadolint and static check pac pipeline so PR changes are used in test

ci/images/ci-runner/hack/bin/destroy-cluster.sh
Output the kubeconfig information and how to connect to the ci-runner.
=> Improve CI logs in case of failure

operator/test/test.sh
from https://github.com/openshift-pipelines/pipeline-service/pull/624 have seen 2 forms of hiccups
1) a pruner pod shows up on the initial listing, but then is gone when we try to get logs for it 
2) one of the results ns pods during the test has the restricted scc
Have also uncovered that the postrgesql and minio tenant storage pods end up privileged; as developer only pods, we are exempting those; see discussion in https://redhat-internal.slack.com/archives/C032EJ007C0/p1682557848053629 
Also adding the pod name to any error logs
Also checking everyone before calling `exit 1`
=> rework pod security and host network checks

developer/openshift/gitops/argocd/pipeline-service/kustomization.yaml, developer/openshift/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml, operator/gitops/argocd/pipeline-service/tekton-chains/kustomization.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/delete-postgres-configmap.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/delete-postgres-service.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/delete-postgres-statefulset.yaml, operator/gitops/argocd/pipeline-service/tekton-results/base/kustomization.yaml
This removes deprecation warning when applying kustomize to the files
=> Update kustomization files to latest standard

ci/docs/continuous_integation.md
* Add information for login to cluster
* Add information for debugging cluster setup
=> added debuging cluster setup in developer documentation

operator/gitops/argocd/pipeline-service/openshift-pipelines/allow-argocd-to-manage.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/kustomization.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/pipelines-scc.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml, operator/gitops/argocd/pipeline-service/tekton-chains/chains-secrets-config.yaml, operator/test/manifests/test/tekton-chains/public-key.yaml, operator/test/manifests/test/tekton-chains/simple-copy-pipeline.yaml, operator/test/test.sh
The PR has 3 commits. This is because some of the changes are temporary and will need to be rolled back in the future.
=> Disable pipeline SA

operator/test/manifests/setup/pipeline-service/appstudio-pipeline-service-account.yaml
see https://github.com/redhat-appstudio/infra-deployments/pull/1836
=> moving off of csi-scc / sharedresources in rhtap

shared/config/dependencies.sh
Generated by developer/images/dependencies-update/hack/bin/update.sh
=> [FREEZE] Update binaries

operator/gitops/argocd/pipeline-service/metrics-exporter/clusterrole.yaml
Needed for https://github.com/openshift-pipelines/pipeline-service-exporter/pull/23 changes
=> PLNSRVCE-1307: add get crds, wach pipelineruns, to exporter rbac

operator/gitops/argocd/pipeline-service/pipelines-as-code/controller-sync.yaml, operator/gitops/argocd/pipeline-service/pipelines-as-code/kustomization.yaml, operator/gitops/argocd/pipeline-service/pipelines-as-code/watcher-sync.yaml
Add more ArgoCD sync waves and phases
https://issues.redhat.com/browse/PLNSRVCE-1285?filter=-1
=> Add more ArgoCD sync waves and phases

developer/openshift/gitops/argocd/pipeline-service-storage.yaml, developer/openshift/gitops/argocd/pipeline-service-storage/minio/tenant/tenant.yaml
Cleanup Minio.
Remove console service, because it is disabled.
Remove skip validation workaround for ArgoCD storage app.
=> Cleanup minio tenant config

operator/gitops/argocd/pipeline-service/pipelines-as-code/kustomization.yaml
This reverts commit 9df510b84d2c484450e96255407b88e28856b66a. This is related to SRVKP-3134.
=> Revert "Upgrade PaC version to 0.17.3"

shared/hack/install.sh
@xinredhat FYI. Looks like you forgot to test the build of the ci-runner image.
=> Fix ROSA installation

.tekton/update-dependencies.yaml, developer/images/devenv/Dockerfile
Also change the update-dependencies pipeline to run only on main.
=> Update devenv image

.tekton/tasks/deploy-cluster.yaml, .tekton/tasks/destroy-cluster.yaml, .tekton/tasks/destroy-existing-cluster.yaml, ci/images/ci-runner/hack/bin/cleanup-expired-clusters.sh, ci/images/ci-runner/hack/bin/deploy-cluster.sh, ci/images/ci-runner/hack/bin/destroy-cluster.sh
As PR https://github.com/redhat-appstudio/infra-deployments/pull/2012 is merged, we can enable CI to load secrets as environment variables in Pipeilnes.
=> PLNSRVCE-1154: Move CI to StoneSoup Prod MVP

ci/images/ci-runner/hack/bin/cleanup-expired-clusters.sh, ci/images/ci-runner/hack/bin/destroy-cluster.sh
* Fix destroy-cluster failing because of an unset var
=> Fix CI issues

.tekton/pipeline-service-test.yaml, .tekton/pipeline-service-upgrade-test.yaml
see https://github.com/openshift-pipelines/pipeline-service/pull/704#issuecomment-1634800837
=> move ci tests to supported 4.12.x version

operator/gitops/argocd/pipeline-service/tekton-results/config.env, operator/gitops/argocd/pipeline-service/tekton-results/delete-postgres-configmap.yaml, operator/gitops/argocd/pipeline-service/tekton-results/delete-postgres-service.yaml, operator/gitops/argocd/pipeline-service/tekton-results/delete-postgres-statefulset.yaml, operator/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml
- remove database patches
- replace resource with base-only overlay
- Refer PLNSRVCE-1256
=> update tekton-results manifests to use overlays

operator/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml
Include tekton pipelines webhook validation fix from downstream tekton results
=> Fix pipeline webhook validation error

.tekton/pipeline-service-images-test.yaml, developer/hack/build-images-buildah.sh, developer/images/devenv/Dockerfile
Add a CI to verify it the docker images can be built successfully before merging to main branch
=> PLNSRVCE-1096:Add CI to docker images

.tekton/infra-deployment-push.yaml, .tekton/stonesoup-e2e-test.yaml
* Fix dashboard path in infra-deployment-push
* Upgrade rosa version in stonesoup-e2e-test
=> Fix broken pipelines

operator/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml, operator/gitops/compute/pipeline-service-manager/role.yaml
https://github.com/openshift-pipelines/tektoncd-results/tree/downstream-0.7.0-02
=> update tekton results

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml
=> remove embedded-status from tekton-config

developer/openshift/gitops/argocd/pipeline-service-o11y/appstudio-grafana/allow-argocd-to-manage.yaml, developer/openshift/gitops/argocd/pipeline-service-o11y/appstudio-prometheus/allow-argocd-to-manage.yaml, developer/openshift/gitops/argocd/pipeline-service-o11y/appstudio-prometheus/kustomization.yaml
Fixes #738 
- Fix broken repository references in the kustomize file
- Fix permission for argoCD
=> Fix monitoring stack for development

operator/gitops/argocd/pipeline-service/openshift-pipelines/chains-observability-service.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/chains-service-monitor.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/kustomization.yaml
=> add ServiceMonitor for tekton chains

.tekton/tasks/update-repository.yaml
* Use the existing GitHubApp to manage changes to the repository
* Try to the make the task generic enough so it can be submitted to redhat-appstudio/build-definitions
=> Refactor update-dependencies 2/2

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
Sprayproxy is running on host clusters and actual data will only be visualized there. On the member clusters no data will be visualized.
=> Add Sprayproxy Grafana panels

.tekton/infra-deployment-push.yaml
On image push fails send slack notification on pipeline-service team channel.
=> PLNSRVCE-1349: Configure slack notification on push fail

.tekton/test-pipeline-service-static-code-analysis.yaml, ci/images/static-checks/Dockerfile, ci/images/static-checks/content/bin/grafana-dashboards.sh
CI is expected to fail on the new task, as the image does not contain the script yet.
=> Add CI task to validate the Grafana dashboards

developer/openshift/README.md
* Correct the app name
* Update README
=> Update dev docs

ci/images/ci-runner/hack/bin/deploy-cluster.sh
This is the configuration recommended by HCP.
=> Update CI HCP configuration

operator/gitops/argocd/pipeline-service/metrics-exporter/kustomization.yaml
Will close if https://github.com/openshift-pipelines/pipeline-service/pull/797 starts passing CI
=> replace https://github.com/openshift-pipelines/pipeline-service/pull/797 to rebase in CI fixes

ci/images/ci-runner/hack/bin/run-plnsvc-test.sh, developer/openshift/dev_setup.sh, developer/openshift/utils.sh
This PR is to fix issue of  [PLNSRVCE-1492](https://issues.redhat.com/browse/PLNSRVCE-1492)
=> fix issues of pipeline-service test

operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-config.yaml
Delete PipelineRuns 10 minutes after completion.
=> Enable completed_run_grace_period for tekton-results

operator/gitops/argocd/pipeline-service/openshift-pipelines/bugfix-pac-gitauth-secrets.yaml, operator/gitops/argocd/pipeline-service/openshift-pipelines/kustomization.yaml
This fix is temporary and meant to be reverted once the issue is solved in PaC.
=> Create a CronJob to fix RHTAPBUGS-256

operator/gitops/argocd/pipeline-service/openshift-pipelines/bugfix-pac-gitauth-secrets.yaml
Fix the query that retrieves the list of old secrets
=> Fix pac-secret-reaper CronJob

developer/images/devenv/Dockerfile
=> Bump devenv base image

operator/gitops/argocd/pipeline-service/tekton-results/api-db-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-kube-rbac-proxy.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-migrator-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-route.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-s3-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-service-sync.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-service-tls.yaml, operator/gitops/argocd/pipeline-service/tekton-results/api-sync.yaml, operator/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml, operator/gitops/argocd/pipeline-service/tekton-results/service-monitor.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-kube-rbac-proxy.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-logging-rbac.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-logging.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-rbac.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-service-sync.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-sync.yaml
Remove namespaces from individual yamls.
=> Use namespace best practices for kustomize

DEPENDENCIES.md, operator/gitops/argocd/pipeline-service/openshift-pipelines/openshift-operator.yaml
=> Upgrade OSP to 1.13

.tekton/open-infra-deployment-pr.yaml
Fix failure from [pr](https://github.com/openshift-pipelines/pipeline-service/pull/867)
=> Fix infra-update failure

ci/images/ci-runner/hack/bin/copy-plnsvc-code.sh
=> Improve CI stability

operator/gitops/argocd/pipeline-service/tekton-results/watcher-config.yaml
=> Renabling check_owner

.tekton/cleanup-existing-clusters.yaml, .tekton/open-infra-deployment-pr.yaml, .tekton/pipeline-service-upgrade-test-ocp-414.yaml, .tekton/pipeline/test-pipeline-service-deployment.yaml, .tekton/pipeline/test-pipeline-service-upgrade.yaml, .tekton/pipeline/test-rhtap-e2e.yaml, .tekton/pipeline/update-repository.yaml, .tekton/tasks/deploy-cluster.yaml, .tekton/tasks/deploy-pipeline-service.yaml, .tekton/tasks/destroy-cluster.yaml, .tekton/tasks/destroy-existing-cluster.yaml, .tekton/tasks/generate-cluster-name.yaml, .tekton/tasks/run-rhtap-e2e.yaml, .tekton/tasks/setup-ci-runner-container.yaml, .tekton/tasks/test-pipeline-service.yaml, .tekton/tasks/update-repository.yaml, .tekton/test-docker-images-build.yaml, .tekton/test-pipeline-service-deployment-ocp-414.yaml, .tekton/test-pipeline-service-static-code-analysis.yaml, .tekton/test-rhtap-e2e.yaml, .tekton/update-dependencies.yaml, operator/test/manifests/test/metrics/curl-metrics-service-pipeline.yaml, operator/test/manifests/test/tekton-chains/public-key.yaml, operator/test/manifests/test/tekton-chains/simple-copy-pipeline.yaml, operator/test/manifests/test/tekton-chains/tekton-chains-metrics.yaml
=> Use tekton.dev/v1 in pipelines/tasks

.tekton/open-infra-deployment-pr.yaml
=> Fix API v1 migration

.tekton/open-infra-deployment-pr.yaml
`oc kustomize` does not have `build` command.
=> Fix kustomize command

operator/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml, operator/test/test.sh
replaces https://github.com/openshift-pipelines/pipeline-service/pull/966 whose rebase somehow go in a bad state
=> tektoncd-results update

operator/gitops/argocd/pipeline-service/tekton-results/api-migrator-config.yaml, operator/gitops/argocd/pipeline-service/tekton-results/kustomization.yaml, operator/gitops/argocd/pipeline-service/tekton-results/watcher-config.yaml
prod currently at 1c5b3054ffb52f172fda31587d7dfd88a9724c8f
remove the threadiness to 32
migrator benign but reverting to simplify things
=> temporarily revert results to current prod level to simplify switch to nightlies

operator/gitops/argocd/pipeline-service/openshift-pipelines/bugfix-pac-gitauth-secrets.yaml
https://github.com/redhat-appstudio/infra-deployments/pull/3481 introduced change to the pipeline-service deploy.yaml files we generate automatically overriding those changes. Here we move the change to the pipeline-service repo.
=> Add konflux-ci namespace to cleaning secrets script

.tekton/open-infra-deployment-pr-osp-nightly.yaml, .tekton/open-infra-deployment-pr.yaml
https://github.com/redhat-appstudio/infra-deployments/pull/3594#discussion_r1598445273
=> pin results images for now until we verify mem leak fix

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
=> filter out NotFound from Results API Success Rate Grafana Panel

.tekton/open-infra-deployment-pr-osp-nightly.yaml, .tekton/open-infra-deployment-pr.yaml
turn off what was done in https://github.com/openshift-pipelines/pipeline-service/pull/997 
=> unpin results images to try new mem leak fixes

.tekton/tasks/deploy-cluster.yaml, .tekton/tasks/destroy-cluster.yaml, .tekton/tasks/destroy-existing-cluster.yaml, ci/images/ci-runner/Dockerfile, ci/images/ci-runner/hack/bin/deploy-cluster.sh, ci/images/e2e-test-runner/Dockerfile, developer/images/dependencies-update/Dockerfile
=> changed aws region form us-east1 to ca-central-1

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
Also fixing issues with older panels as various var substitutions only work in App SRE, some metrics names were incorrect, and some 'prometheus' filters were no longer (if ever) valid
=> SRVKP-4523: add alert related deadlock / crashloop panels for core tekton controllers

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
=> adjust some of the new panel intervals to line up with alerts

.tekton/tasks/deploy-cluster.yaml, .tekton/tasks/destroy-cluster.yaml, .tekton/tasks/destroy-existing-cluster.yaml, ci/images/ci-runner/hack/bin/deploy-cluster.sh
=> revert back to us-eas1-1 region

operator/gitops/argocd/grafana/dashboards/pipeline-service-dashboard.json
Add Deadlocked ResolutionRequests panel same as App SRE dashboard and make changes in Pipelines controller restart panel as per App SRE dashboard
=> Add Deadlocked ResolutionRequests panel and update Pipelines controller restart panel
